In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\Public\Documents\Axel\libertadores26-data\matchStats\csv\fotmob_match_stats.csv')
df.tail()

,matchId,matchRound,homeTeamName,homeTeamid,awayTeamName,awayTeamid,home_goals,away_goals,ball_possession_home,ball_possession_away,...,ground_duels_won_home,ground_duels_won_away,aerial_won_home,aerial_won_away,dribbles_succeeded_home,dribbles_succeeded_away,yellow_cards_home,yellow_cards_away,red_cards_home,red_cards_away
90,5261485,Group Stage - Round 6,Fluminense,9863,Deportivo La Guaira,176496,3,1,56,44,...,35 (48%),38 (52%),11 (73%),4 (27%),11 (65%),10 (63%),0,0,0,0
91,5261508,Group Stage - Round 6,Cerro Porteno,6295,Sporting Cristal,1848,2,0,51,49,...,37 (53%),33 (47%),16 (70%),7 (30%),6 (43%),5 (50%),0,0,0,0
92,5261509,Group Stage - Round 6,Palmeiras,10283,Junior FC,2254,4,1,49,51,...,55 (65%),30 (35%),6 (55%),5 (45%),15 (60%),8 (40%),0,0,0,0
93,5261542,Group Stage - Round 6,Boca Juniors,10077,Universidad Catolica,6458,0,1,71,29,...,46 (58%),34 (43%),23 (59%),16 (41%),13 (46%),2 (25%),0,0,0,0
94,5261543,Group Stage - Round 6,Cruzeiro,9781,Barcelona SC,6453,4,0,59,41,...,32 (53%),28 (47%),10 (53%),9 (47%),7 (58%),6 (100%),0,0,0,0

In [3]:
df.columns

Index(['matchId', 'matchRound', 'homeTeamName', 'homeTeamid', 'awayTeamName',
       'awayTeamid', 'home_goals', 'away_goals', 'ball_possession_home',
       'ball_possession_away', 'big_chances_home', 'big_chances_away',
       'big_chances_missed_home', 'big_chances_missed_away', 'fouls_home',
       'fouls_away', 'corners_home', 'corners_away', 'total_shots_home',
       'total_shots_away', 'shots_off_target_home', 'shots_off_target_away',
       'shots_on_target_home', 'shots_on_target_away', 'blocked_shots_home',
       'blocked_shots_away', 'hit_woodwork_home', 'hit_woodwork_away',
       'shots_inside_box_home', 'shots_inside_box_away',
       'shots_outside_box_home', 'shots_outside_box_away', 'xG_home',
       'xG_away', 'xG_open_play_home', 'xG_open_play_away', 'xG_set_play_home',
       'xG_set_play_away', 'xG_non_penalty_home', 'xG_non_penalty_away',
       'xGOT_home', 'xGOT_away', 'passes_home', 'passes_away',
       'accurate_passes_home', 'accurate_passes_away', 'own_half_passes_home',
       'own_half_passes_away', 'opposition_half_passes_home',
       'opposition_half_passes_away', 'accurate_long_passes_home',
       'accurate_long_passes_away', 'accurate_crosses_home',
       'accurate_crosses_away', 'throws_home', 'throws_away',
       'touches_opp_box_home', 'touches_opp_box_away', 'offsides_home',
       'offsides_away', 'tackles_won_home', 'tackles_won_away',
       'interceptions_home', 'interceptions_away', 'blocks_home',
       'blocks_away', 'clearances_home', 'clearances_away',
       'keeper_saves_home', 'keeper_saves_away', 'duel_won_home',
       'duel_won_away', 'ground_duels_won_home', 'ground_duels_won_away',
       'aerial_won_home', 'aerial_won_away', 'dribbles_succeeded_home',
       'dribbles_succeeded_away', 'yellow_cards_home', 'yellow_cards_away',
       'red_cards_home', 'red_cards_away'],
      dtype='str')

In [3]:
# Get the row with the highest ball possession playing home
df.loc[[df['ball_possession_home'].idxmax()], ['matchRound', 'homeTeamName', 'awayTeamName', 'home_goals', 'away_goals', 'ball_possession_home', 'ball_possession_away']]

,matchRound,homeTeamName,awayTeamName,home_goals,away_goals,ball_possession_home,ball_possession_away
46,3,Corinthians,Club Atletico Penarol,2,0,78,22

In [29]:
# Get the row with the lowest ball possession playing home
df.loc[[df['ball_possession_home'].idxmin()], ['matchRound', 'homeTeamName', 'awayTeamName', 'home_goals', 'away_goals', 'ball_possession_home', 'ball_possession_away']]

,matchRound,homeTeamName,awayTeamName,home_goals,away_goals,ball_possession_home,ball_possession_away
55,4,Independiente Rivadavia,Fluminense,1,1,27,73

In [31]:
# Get the row with the highest ball possession playing away
df.loc[[df['ball_possession_away'].idxmax()], ['matchRound', 'homeTeamName', 'awayTeamName', 'home_goals', 'away_goals', 'ball_possession_home', 'ball_possession_away']]

,matchRound,homeTeamName,awayTeamName,home_goals,away_goals,ball_possession_home,ball_possession_away
55,4,Independiente Rivadavia,Fluminense,1,1,27,73

In [32]:
# Get the row with the lowest ball possession playing away
df.loc[[df['ball_possession_away'].idxmin()], ['matchRound', 'homeTeamName', 'awayTeamName', 'home_goals', 'away_goals', 'ball_possession_home', 'ball_possession_away']]

,matchRound,homeTeamName,awayTeamName,home_goals,away_goals,ball_possession_home,ball_possession_away
46,3,Corinthians,Club Atletico Penarol,2,0,78,22

In [4]:
# Get the top 10 with the most ball possession playing HOME
df.nlargest(10, 'ball_possession_home')[['matchRound', 'homeTeamName', 'awayTeamName', 'home_goals', 'away_goals', 'ball_possession_home', 'ball_possession_away']]

,matchRound,homeTeamName,awayTeamName,home_goals,away_goals,ball_possession_home,ball_possession_away
46,3,Corinthians,Club Atletico Penarol,2,0,78,22
89,Group Stage - Round 6,Corinthians,Club Atletico Platense,0,2,77,23
78,5,Universidad Catolica,Barcelona SC,2,0,76,24
64,5,Fluminense,Bolivar,2,1,74,26
73,5,Palmeiras,Cerro Porteno,0,1,74,26
20,2,Bolivar,Deportivo La Guaira,1,1,72,28
81,6,Estudiantes,Independiente Medellin,1,0,72,28
26,2,Fluminense,Independiente Rivadavia,1,2,71,29
93,Group Stage - Round 6,Boca Juniors,Universidad Catolica,0,1,71,29
6,1,Coquimbo Unido,Nacional,1,1,68,32

In [5]:
# Get the top 10 with the lowest ball possession playing HOME using nsmallest()
df.nsmallest(10, 'ball_possession_home')[['matchRound', 'homeTeamName', 'awayTeamName', 'home_goals', 'away_goals', 'ball_possession_home', 'ball_possession_away']]

,matchRound,homeTeamName,awayTeamName,home_goals,away_goals,ball_possession_home,ball_possession_away
55,4,Independiente Rivadavia,Fluminense,1,1,27,73
51,4,Universidad Central,Independiente del Valle,2,0,32,68
24,2,Libertad,Rosario Central,0,1,33,67
63,5,Coquimbo Unido,Tolima,3,0,33,67
83,6,Nacional,Coquimbo Unido,1,0,33,67
41,3,Cerro Porteno,Palmeiras,1,1,34,66
77,5,Club Atletico Penarol,Corinthians,1,1,35,65
0,1,Deportivo La Guaira,Fluminense,0,0,36,64
1,1,Independiente Rivadavia,Bolivar,1,0,36,64
21,2,LDU de Quito,Mirassol,2,0,39,61

In [6]:
# Promedio de posesión por equipo como local
promedio_poss_local = df.groupby('homeTeamName')['ball_possession_home'].mean().reset_index()
promedio_poss_local

                 homeTeamName  ball_possession_home
0                Always Ready             58.666667
1                Barcelona SC             55.000000
2                Boca Juniors             62.666667
3                     Bolivar             62.333333
4               Cerro Porteno             43.666667
5       Club Atletico Penarol             50.000000
6      Club Atletico Platense             54.666667
7              Coquimbo Unido             51.000000
8                 Corinthians             73.666667
9                    Cruzeiro             61.666667
10                   Cusco FC             57.666667
11        Deportivo La Guaira             46.333333
12                Estudiantes             60.000000
13                   Flamengo             64.666667
14                 Fluminense             67.000000
15     Independiente Medellin             63.500000
16    Independiente Rivadavia             38.333333
17    Independiente del Valle             62.000000
18                  Junior FC             53.000000
19               LDU de Quito             50.666667
20                      Lanus             56.000000
21                   Libertad             43.666667
22                   Mirassol             47.666667
23                   Nacional             40.666667
24                  Palmeiras             62.666667
25            Rosario Central             58.000000
26                   Santa Fe             50.000000
27           Sporting Cristal             53.000000
28                     Tolima             65.333333
29       Universidad Catolica             57.666667
30        Universidad Central             38.333333
31  Universitario de Deportes             57.333333

In [7]:
# Promedio de posesión por equipo como local
promedio_poss_local = df.groupby('homeTeamName')['ball_possession_home'].mean().reset_index()
promedio_poss_local.columns = ['Equipo', 'Promedio_Posesion_Local']
promedio_poss_local = promedio_poss_local.sort_values('Promedio_Posesion_Local', ascending=False)

# Ver el equipo con mayor promedio
equipo_max_promedio = promedio_poss_local.iloc[0]
print(f"Equipo con mayor promedio de posesión como local: {equipo_max_promedio['Equipo']} - {equipo_max_promedio['Promedio_Posesion_Local']:.2f}%")

Equipo con mayor promedio de posesión como local: Corinthians - 73.67%

In [10]:
# Pomedio de posesión por equipo local
resultado = df.groupby('homeTeamName').agg({
    'ball_possession_home': ['mean', 'count', 'sum']
}).reset_index()

# Ordenar de mayor a menor por la columna 'mean'
resultado = resultado.sort_values(('ball_possession_home', 'mean'), ascending=False)

resultado

                 homeTeamName ball_possession_home
                                              mean count  sum
8                 Corinthians            73.666667     3  221
14                 Fluminense            67.000000     3  201
28                     Tolima            65.333333     3  196
13                   Flamengo            64.666667     3  194
15     Independiente Medellin            63.500000     2  127
2                Boca Juniors            62.666667     3  188
24                  Palmeiras            62.666667     3  188
3                     Bolivar            62.333333     3  187
17    Independiente del Valle            62.000000     3  186
9                    Cruzeiro            61.666667     3  185
12                Estudiantes            60.000000     3  180
0                Always Ready            58.666667     3  176
25            Rosario Central            58.000000     3  174
10                   Cusco FC            57.666667     3  173
29       Universidad Catolica            57.666667     3  173
31  Universitario de Deportes            57.333333     3  172
20                      Lanus            56.000000     3  168
1                Barcelona SC            55.000000     3  165
6      Club Atletico Platense            54.666667     3  164
18                  Junior FC            53.000000     3  159
27           Sporting Cristal            53.000000     3  159
7              Coquimbo Unido            51.000000     3  153
19               LDU de Quito            50.666667     3  152
5       Club Atletico Penarol            50.000000     3  150
26                   Santa Fe            50.000000     3  150
22                   Mirassol            47.666667     3  143
11        Deportivo La Guaira            46.333333     3  139
4               Cerro Porteno            43.666667     3  131
21                   Libertad            43.666667     3  131
23                   Nacional            40.666667     3  122
16    Independiente Rivadavia            38.333333     3  115
30        Universidad Central            38.333333     3  115

In [11]:
# Pomedio de posesión por equipo visitante
resultado = df.groupby('awayTeamName').agg({
    'ball_possession_away': ['mean', 'count', 'sum']
}).reset_index()

# Ordenar de mayor a menor por la columna 'mean'
resultado = resultado.sort_values(('ball_possession_away', 'mean'), ascending=False)

resultado

                 awayTeamName ball_possession_away
                                              mean count  sum
14                 Fluminense            62.333333     3  187
24                  Palmeiras            60.333333     3  181
28                     Tolima            59.333333     3  178
25            Rosario Central            56.333333     3  169
8                 Corinthians            55.666667     3  167
17    Independiente del Valle            55.333333     3  166
22                   Mirassol            54.000000     3  162
18                  Junior FC            49.666667     3  149
13                   Flamengo            49.000000     2   98
2                Boca Juniors            48.666667     3  146
21                   Libertad            48.333333     3  145
3                     Bolivar            47.333333     3  142
9                    Cruzeiro            46.333333     3  139
0                Always Ready            45.333333     3  136
27           Sporting Cristal            44.666667     3  134
31  Universitario de Deportes            44.666667     3  134
20                      Lanus            44.000000     3  132
7              Coquimbo Unido            43.666667     3  131
19               LDU de Quito            43.666667     3  131
26                   Santa Fe            40.666667     3  122
11        Deportivo La Guaira            40.000000     3  120
6      Club Atletico Platense            39.000000     3  117
30        Universidad Central            38.000000     3  114
23                   Nacional            38.000000     3  114
10                   Cusco FC            37.666667     3  113
5       Club Atletico Penarol            36.333333     3  109
16    Independiente Rivadavia            36.333333     3  109
12                Estudiantes            36.000000     3  108
15     Independiente Medellin            35.666667     3  107
1                Barcelona SC            34.000000     3  102
29       Universidad Catolica            34.000000     3  102
4               Cerro Porteno            33.000000     3   99