In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\Public\Documents\Axel\wcup26\matchStats\csv\fotmob_match_stats.csv')
df

,matchId,matchRound,homeTeamName,homeTeamid,awayTeamName,awayTeamid,home_goals,away_goals,ball_possession_home,ball_possession_away,...,ground_duels_won_home,ground_duels_won_away,aerial_won_home,aerial_won_away,dribbles_succeeded_home,dribbles_succeeded_away,yellow_cards_home,yellow_cards_away,red_cards_home,red_cards_away
0,4667751,1,Mexico,6710,South Africa,6316,2,0,60,40,...,32 (55%),26 (45%),15 (68%),7 (32%),9 (60%),1 (17%),1,2,1,2
1,4667752,1,South Korea,7804,Czechia,8496,2,1,62,38,...,29 (57%),22 (43%),27 (63%),16 (37%),8 (57%),4 (57%),1,0,0,0
2,4667757,1,Canada,5810,Bosnia and Herzegovina,10106,1,1,61,39,...,50 (58%),36 (42%),20 (32%),43 (68%),7 (47%),5 (23%),2,3,0,0
3,4667771,1,USA,6713,Paraguay,6724,4,1,65,35,...,47 (55%),39 (45%),18 (53%),16 (47%),22 (63%),6 (60%),1,5,0,0
4,4667758,1,Qatar,5902,Switzerland,6717,1,1,32,68,...,26 (49%),27 (51%),10 (50%),10 (50%),2 (50%),7 (54%),2,1,0,0
5,4667764,1,Brazil,8256,Morocco,6262,1,1,51,49,...,41 (41%),58 (59%),12 (75%),4 (25%),5 (19%),16 (55%),2,0,0,0
6,4667765,1,Haiti,5934,Scotland,8498,0,1,54,46,...,38 (50%),38 (50%),13 (38%),21 (62%),6 (43%),5 (38%),1,3,0,0
7,4667772,1,Australia,6716,Turkiye,6595,2,0,28,72,...,27 (48%),29 (52%),15 (47%),17 (53%),8 (73%),5 (36%),0,1,0,0
8,4667777,1,Germany,8570,Curacao,287981,7,1,65,35,...,38 (46%),45 (54%),9 (64%),5 (36%),9 (50%),12 (57%),0,0,0,0
9,4667783,1,Netherlands,6708,Japan,6715,2,2,60,40,...,25 (54%),21 (46%),21 (75%),7 (25%),8 (53%),3 (33%),3,0,0,0
10,4667778,1,Ivory Coast,6709,Ecuador,6707,1,0,48,52,...,41 (55%),33 (45%),17 (61%),11 (39%),14 (67%),3 (30%),3,1,0,0
11,4667784,1,Sweden,8520,Tunisia,6719,5,1,49,51,...,26 (42%),36 (58%),15 (50%),15 (50%),5 (42%),7 (44%),0,1,0,0
12,4667798,1,Spain,6720,Cape Verde,5888,0,0,74,26,...,21 (40%),31 (60%),19 (68%),9 (32%),7 (54%),4 (36%),1,1,0,0
13,4667790,1,Belgium,8263,Egypt,10255,1,1,54,46,...,38 (44%),49 (56%),14 (64%),8 (36%),7 (37%),7 (54%),2,2,0,0
14,4667799,1,Saudi Arabia,7795,Uruguay,5796,1,1,33,67,...,18 (45%),22 (55%),22 (52%),20 (48%),3 (60%),8 (67%),1,0,0,0
15,4667791,1,Iran,6711,New Zealand,5820,2,2,48,52,...,29 (51%),28 (49%),25 (63%),15 (38%),4 (36%),6 (50%),1,0,0,0
16,4667804,1,France,6723,Senegal,6395,3,1,54,46,...,31 (53%),27 (47%),12 (60%),8 (40%),5 (31%),8 (62%),0,0,0,0
17,4667805,1,Iraq,5819,Norway,8492,1,4,39,61,...,42 (58%),31 (42%),10 (37%),17 (63%),10 (48%),5 (29%),1,0,0,0
18,4667812,1,Argentina,6706,Algeria,6317,3,0,48,52,...,36 (49%),38 (51%),3 (38%),5 (63%),2 (22%),8 (35%),0,0,0,0
19,4667813,1,Austria,8255,Jordan,5816,3,1,63,37,...,28 (42%),39 (58%),16 (64%),9 (36%),5 (36%),15 (63%),1,0,0,0
20,4667819,1,Portugal,8361,DR Congo,6321,1,1,75,25,...,25 (42%),34 (58%),9 (53%),8 (47%),5 (42%),8 (53%),3,1,0,0

In [10]:
df.columns

Index(['matchId', 'matchRound', 'homeTeamName', 'homeTeamid', 'awayTeamName',
       'awayTeamid', 'home_goals', 'away_goals', 'ball_possession_home',
       'ball_possession_away', 'big_chances_home', 'big_chances_away',
       'big_chances_missed_home', 'big_chances_missed_away', 'fouls_home',
       'fouls_away', 'corners_home', 'corners_away', 'total_shots_home',
       'total_shots_away', 'shots_off_target_home', 'shots_off_target_away',
       'shots_on_target_home', 'shots_on_target_away', 'blocked_shots_home',
       'blocked_shots_away', 'hit_woodwork_home', 'hit_woodwork_away',
       'shots_inside_box_home', 'shots_inside_box_away',
       'shots_outside_box_home', 'shots_outside_box_away', 'xG_home',
       'xG_away', 'xG_open_play_home', 'xG_open_play_away', 'xG_set_play_home',
       'xG_set_play_away', 'xG_non_penalty_home', 'xG_non_penalty_away',
       'xGOT_home', 'xGOT_away', 'passes_home', 'passes_away',
       'accurate_passes_home', 'accurate_passes_away', 'own_half_passes_home',
       'own_half_passes_away', 'opposition_half_passes_home',
       'opposition_half_passes_away', 'accurate_long_passes_home',
       'accurate_long_passes_away', 'accurate_crosses_home',
       'accurate_crosses_away', 'throws_home', 'throws_away',
       'touches_opp_box_home', 'touches_opp_box_away', 'offsides_home',
       'offsides_away', 'tackles_won_home', 'tackles_won_away',
       'interceptions_home', 'interceptions_away', 'blocks_home',
       'blocks_away', 'clearances_home', 'clearances_away',
       'keeper_saves_home', 'keeper_saves_away', 'duel_won_home',
       'duel_won_away', 'ground_duels_won_home', 'ground_duels_won_away',
       'aerial_won_home', 'aerial_won_away', 'dribbles_succeeded_home',
       'dribbles_succeeded_away', 'yellow_cards_home', 'yellow_cards_away',
       'red_cards_home', 'red_cards_away'],
      dtype='str')

In [3]:
# p90 minutes MEAN

# xG_home, xG_open_play_home, xG_set_play_home, xG_non_penalty_home, xGOT_home

# Create a dataframe with home teams data
xG_mean_home_df = df[['homeTeamName', 'homeTeamid', 'xG_home', 'xG_open_play_home', 'xG_set_play_home', 'xG_non_penalty_home', 'xGOT_home']].rename(
    columns={
        'homeTeamName': 'teamName',
        'homeTeamid': 'teamId',
        'xG_home': 'xG',
        'xG_open_play_home': 'xG_open_play',
        'xG_set_play_home': 'xG_set_play',
        'xG_non_penalty_home': 'xG_non_penalty',
        'xGOT_home': 'xGOT'
    }
)

# Create a dataframe with away teams data
xG_mean_away_df = df[['awayTeamName', 'awayTeamid', 'xG_away', 'xG_open_play_away', 'xG_set_play_away', 'xG_non_penalty_away', 'xGOT_away']].rename(
    columns={
        'awayTeamName': 'teamName',
        'awayTeamid': 'teamId',
        'xG_away': 'xG',
        'xG_open_play_away': 'xG_open_play',
        'xG_set_play_away': 'xG_set_play',
        'xG_non_penalty_away': 'xG_non_penalty',
        'xGOT_away': 'xGOT'
    }
)

# Stack both dataframes together
xG_mean_possession = pd.concat([xG_mean_home_df, xG_mean_away_df], ignore_index=True)

xG_mean_df = (
    xG_mean_possession
    .groupby(['teamId', 'teamName']).agg(
          matches=('teamName', 'size'),
          avg_xG=('xG', 'mean'),
          total_xG=('xG', 'sum'),
          avg_xG_open_play=('xG_open_play', 'mean'),
          avg_xG_set_play=('xG_set_play', 'mean'),
          avg_xG_non_penalty=('xG_non_penalty', 'mean')
      )
      .sort_values('avg_xG', ascending=False)
      .reset_index()
)

xG_mean_df

,teamId,teamName,matches,avg_xG,total_xG,avg_xG_open_play,avg_xG_set_play,avg_xG_non_penalty
0,8570,Germany,1,4.22,4.22,2.99,0.44,3.43
1,6717,Switzerland,1,3.20,3.20,1.72,0.69,2.41
2,8492,Norway,1,2.52,2.52,1.99,0.53,2.52
3,7804,South Korea,1,2.30,2.30,2.21,0.09,2.30
4,6720,Spain,1,2.10,2.10,1.67,0.43,2.10
5,6723,France,1,1.89,1.89,1.89,1.89,2.00
6,5796,Uruguay,1,1.72,1.72,0.85,0.88,1.72
7,8255,Austria,1,1.69,1.69,0.89,0.01,0.90
8,6709,Ivory Coast,1,1.52,1.52,1.42,0.10,1.52
9,6711,Iran,1,1.50,1.50,1.32,0.17,1.50
10,6710,Mexico,1,1.46,1.46,1.14,0.32,1.46
11,6713,USA,1,1.42,1.42,1.36,0.06,1.42
12,6262,Morocco,1,1.37,1.37,1.23,0.14,1.37
13,6595,Turkiye,1,1.36,1.36,1.12,0.24,1.36
14,8520,Sweden,1,1.33,1.33,1.11,0.22,1.33
15,8263,Belgium,1,1.31,1.31,0.80,0.51,1.31
16,8256,Brazil,1,1.26,1.26,1.03,0.23,1.26
17,6706,Argentina,1,1.26,1.26,1.18,0.08,1.26
18,5810,Canada,1,1.25,1.25,0.99,0.25,1.25
19,5820,New Zealand,1,1.24,1.24,0.57,0.67,1.24
20,6716,Australia,1,1.18,1.18,0.53,0.65,1.18
21,10255,Egypt,1,1.07,1.07,0.98,0.09,1.07
22,8498,Scotland,1,1.05,1.05,1.05,0.00,1.05
23,5934,Haiti,1,1.05,1.05,0.99,0.06,1.05
24,6707,Ecuador,1,1.01,1.01,0.65,0.36,1.01
25,10106,Bosnia and Herzegovina,1,0.98,0.98,0.02,0.97,0.98
26,6321,DR Congo,1,0.87,0.87,0.29,0.58,0.87
27,8496,Czechia,1,0.83,0.83,0.20,0.63,0.83
28,5819,Iraq,1,0.80,0.80,0.57,0.23,0.80
29,6708,Netherlands,1,0.78,0.78,0.33,0.45,0.78
30,7795,Saudi Arabia,1,0.66,0.66,0.09,0.57,0.66
31,8361,Portugal,1,0.65,0.65,0.65,0.00,0.65
32,5902,Qatar,1,0.60,0.60,0.52,0.08,0.60
33,6715,Japan,1,0.59,0.59,0.40,0.19,0.59
34,6724,Paraguay,1,0.54,0.54,0.24,0.29,0.54
35,6395,Senegal,1,0.50,0.50,0.50,0.50,0.11
36,5816,Jordan,1,0.46,0.46,0.33,0.13,0.46
37,287981,Curacao,1,0.41,0.41,0.23,0.18,0.41
38,6317,Algeria,1,0.32,0.32,0.18,0.14,0.32
39,6719,Tunisia,1,0.28,0.28,0.05,0.23,0.28
40,5888,Cape Verde,1,0.20,0.20,0.06,0.14,0.20
41,6316,South Africa,1,0.07,0.07,0.06,0.01,0.07

In [4]:
# MEAN

# ball_possession_home

# Create a dataframe with home teams data
mean_home_df = df[['homeTeamName', 'homeTeamid', 'ball_possession_home']].rename(
    columns={
        'homeTeamName': 'teamName',
        'homeTeamid': 'teamId',
        'ball_possession_home': 'ball_possession'
    }
)

# Create a dataframe with away teams data
mean_away_df = df[['awayTeamName', 'awayTeamid', 'ball_possession_away']].rename(
    columns={
        'awayTeamName': 'teamName',
        'awayTeamid': 'teamId',
        'ball_possession_away': 'ball_possession'
    }
)

# Stack both dataframes together
mean_possession = pd.concat([mean_home_df, mean_away_df], ignore_index=True)

# Mean
ball_possession_df = (
    mean_possession
    .groupby(['teamId', 'teamName'], as_index=False)[['ball_possession']]
    .mean()
    .rename(columns={'ball_possession': 'mean_ball_possession'})
    .sort_values('mean_ball_possession', ascending=False)
)

ball_possession_df

    teamId                teamName  mean_ball_possession
33    8361                Portugal                  75.0
25    6720                   Spain                  74.0
13    6595                 Turkiye                  72.0
23    6717             Switzerland                  68.0
0     5796                 Uruguay                  67.0
38    8570                 Germany                  65.0
20    6713                     USA                  65.0
30    8255                 Austria                  63.0
29    7804             South Korea                  62.0
1     5810                  Canada                  61.0
34    8492                  Norway                  61.0
18    6710                  Mexico                  60.0
16    6708             Netherlands                  60.0
26    6723                  France                  54.0
32    8263                 Belgium                  54.0
7     5934                   Haiti                  54.0
4     5820             New Zealand                  52.0
15    6707                 Ecuador                  52.0
10    6317                 Algeria                  52.0
24    6719                 Tunisia                  51.0
31    8256                  Brazil                  51.0
37    8520                  Sweden                  49.0
8     6262                 Morocco                  49.0
14    6706               Argentina                  48.0
19    6711                    Iran                  48.0
17    6709             Ivory Coast                  48.0
40   10255                   Egypt                  46.0
36    8498                Scotland                  46.0
12    6395                 Senegal                  46.0
21    6715                   Japan                  40.0
9     6316            South Africa                  40.0
39   10106  Bosnia and Herzegovina                  39.0
3     5819                    Iraq                  39.0
35    8496                 Czechia                  38.0
2     5816                  Jordan                  37.0
27    6724                Paraguay                  35.0
41  287981                 Curacao                  35.0
28    7795            Saudi Arabia                  33.0
6     5902                   Qatar                  32.0
22    6716               Australia                  28.0
5     5888              Cape Verde                  26.0
11    6321                DR Congo                  25.0

In [5]:
# Columns to SUM

# home_goals, big_chances_home, big_chances_missed_home, corners_home, total_shots_home, shots_off_target_home, blocked_shots_home, hit_woodwork_home, shots_inside_box_home, shots_outside_box_home,
# passes_home, own_half_passes_home, opposition_half_passes_home, throws_home, touches_opp_box_home, offsides_home, tackles_won_home, interceptions_home, blocks_home, clearances_home, keeper_saves_home,
# duel_won_home, yellow_cards_home, red_cards_home

# Create a dataframe with home teams data
home_df = df[['homeTeamName', 'homeTeamid', 'home_goals', 'big_chances_home', 'big_chances_missed_home', 'corners_home', 'total_shots_home', 'shots_off_target_home', 'blocked_shots_home',
              'hit_woodwork_home', 'shots_inside_box_home', 'shots_outside_box_home', 'passes_home', 'own_half_passes_home', 'opposition_half_passes_home', 'throws_home', 'touches_opp_box_home',
              'offsides_home', 'tackles_won_home', 'interceptions_home', 'blocks_home', 'clearances_home', 'keeper_saves_home', 'duel_won_home', 'yellow_cards_home', 'red_cards_home']].rename(
    columns={
        'homeTeamName': 'teamName',
        'homeTeamid': 'teamId',
        'home_goals': 'goals',
        'big_chances_home': 'big_chances',
        'big_chances_missed_home': 'big_chances_missed',
        'corners_home': 'corners',
        'total_shots_home': 'total_shots',
        'shots_off_target_home': 'shots_off_target',
        'blocked_shots_home': 'blocked_shots',
        'hit_woodwork_home': 'hit_woodwork',
        'shots_inside_box_home': 'shots_inside_box',
        'shots_outside_box_home': 'shots_outside_box',
        'passes_home': 'passes',
        'own_half_passes_home': 'own_half_passes',
        'opposition_half_passes_home': 'opposition_half_passes',
        'throws_home': 'throws',
        'touches_opp_box_home': 'touches_opp_box',
        'offsides_home': 'offsides',
        'tackles_won_home': 'tackles_won',
        'interceptions_home': 'interceptions',
        'blocks_home': 'blocks',
        'clearances_home': 'clearances',
        'keeper_saves_home': 'keeper_saves',
        'duel_won_home': 'duel_won',
        'yellow_cards_home': 'yellow_cards',
        'red_cards_home': 'red_cards'
    }
)

# Create a dataframe with away teams data
away_df = df[['awayTeamName', 'awayTeamid', 'away_goals', 'big_chances_away', 'big_chances_missed_away', 'corners_away', 'total_shots_away', 'shots_off_target_away', 'blocked_shots_away',
              'hit_woodwork_away', 'shots_inside_box_away', 'shots_outside_box_away', 'passes_away', 'own_half_passes_away', 'opposition_half_passes_away', 'throws_away', 'touches_opp_box_away',
              'offsides_away', 'tackles_won_away', 'interceptions_away', 'blocks_away', 'clearances_away', 'keeper_saves_away', 'duel_won_away', 'yellow_cards_away', 'red_cards_away']].rename(
    columns={
        'awayTeamName': 'teamName',
        'awayTeamid': 'teamId',
        'away_goals': 'goals',
        'big_chances_away': 'big_chances',
        'big_chances_missed_away': 'big_chances_missed',
        'corners_away': 'corners',
        'total_shots_away': 'total_shots',
        'shots_off_target_away': 'shots_off_target',
        'blocked_shots_away': 'blocked_shots',
        'hit_woodwork_away': 'hit_woodwork',
        'shots_inside_box_away': 'shots_inside_box',
        'shots_outside_box_away': 'shots_outside_box',
        'passes_away': 'passes',
        'own_half_passes_away': 'own_half_passes',
        'opposition_half_passes_away': 'opposition_half_passes',
        'throws_away': 'throws',
        'touches_opp_box_away': 'touches_opp_box',
        'offsides_away': 'offsides',
        'tackles_won_away': 'tackles_won',
        'interceptions_away': 'interceptions',
        'blocks_away': 'blocks',
        'clearances_away': 'clearances',
        'keeper_saves_away': 'keeper_saves',
        'duel_won_away': 'duel_won',
        'yellow_cards_away': 'yellow_cards',
        'red_cards_away': 'red_cards'
    }
)

# Stack both dataframes together
teams_goals = pd.concat([home_df, away_df], ignore_index=True)

# Sum
sum_df = (
    teams_goals
    .groupby(['teamId', 'teamName'], as_index=False)[['goals', 'big_chances', 'big_chances_missed', 'corners', 'total_shots', 'shots_off_target', 'blocked_shots', 'hit_woodwork', 'shots_inside_box',
                                                      'shots_outside_box', 'passes', 'own_half_passes', 'opposition_half_passes', 'throws', 'touches_opp_box', 'offsides', 'tackles_won', 'interceptions',
                                                      'blocks', 'clearances', 'keeper_saves', 'duel_won', 'yellow_cards', 'red_cards']]
    .sum()
    .sort_values('goals', ascending=False)
)

sum_df

,teamId,teamName,goals,big_chances,big_chances_missed,corners,total_shots,shots_off_target,blocked_shots,hit_woodwork,...,touches_opp_box,offsides,tackles_won,interceptions,blocks,clearances,keeper_saves,duel_won,yellow_cards,red_cards
38,8570,Germany,7,63,6,0.0,26,6,8,1,...,63,0,19,12,0,8,1,47,0,0
37,8520,Sweden,5,22,4,0.0,13,3,3,0,...,22,3,14,6,1,23,1,41,0,0
34,8492,Norway,4,25,5,0.0,12,4,3,0,...,25,0,15,2,2,22,0,48,0,0
20,6713,USA,4,53,4,1.0,16,6,4,0,...,53,2,9,9,3,15,0,65,1,0
14,6706,Argentina,3,12,1,0.0,10,4,0,0,...,12,3,27,10,3,17,0,39,0,0
26,6723,France,3,19,4,0.0,11,1,2,0,...,19,1,18,8,1,14,2,43,0,0
30,8255,Austria,3,28,4,1.0,11,6,1,0,...,28,3,17,15,2,24,3,44,1,0
18,6710,Mexico,2,20,2,1.0,16,7,5,1,...,20,1,12,8,0,15,2,47,1,1
4,5820,New Zealand,2,21,2,0.0,14,4,2,0,...,21,0,13,15,5,26,2,43,0,0
21,6715,Japan,2,19,0,0.0,10,6,1,0,...,19,0,11,4,1,32,4,28,0,0
22,6716,Australia,2,18,1,0.0,9,4,1,0,...,18,1,15,7,12,55,8,42,0,0
19,6711,Iran,2,25,2,1.0,17,8,5,1,...,25,2,17,11,1,27,6,54,1,0
29,7804,South Korea,2,24,4,1.0,15,5,4,0,...,24,2,7,9,0,32,3,56,1,0
16,6708,Netherlands,2,33,0,3.0,10,3,1,0,...,33,1,11,7,0,23,1,46,3,0
33,8361,Portugal,1,29,0,3.0,7,4,2,0,...,29,3,12,3,2,10,1,34,3,0
3,5819,Iraq,1,18,1,1.0,11,8,2,0,...,18,1,19,5,3,20,2,52,1,0
2,5816,Jordan,1,21,0,0.0,11,5,2,1,...,21,1,15,12,2,39,1,48,0,0
1,5810,Canada,1,38,2,2.0,13,5,4,1,...,38,1,23,4,0,21,2,70,2,0
0,5796,Uruguay,1,41,2,0.0,27,10,7,1,...,41,6,3,10,1,17,2,42,0,0
32,8263,Belgium,1,30,2,2.0,15,7,5,1,...,30,0,16,10,8,26,2,52,2,0
31,8256,Brazil,1,22,1,2.0,12,4,3,0,...,22,0,23,5,6,23,2,53,2,0
8,6262,Morocco,1,13,2,0.0,14,5,6,0,...,13,1,26,5,3,17,4,62,0,0
6,5902,Qatar,1,8,1,2.0,6,3,0,0,...,8,0,14,11,9,31,5,36,2,0
23,6717,Switzerland,1,42,6,1.0,26,10,9,0,...,42,1,8,7,0,13,3,37,1,0
12,6395,Senegal,1,14,2,0.0,6,3,1,1,...,14,3,14,8,2,17,5,35,0,0
11,6321,DR Congo,1,10,1,1.0,8,3,3,0,...,10,2,17,5,2,27,0,42,1,0
36,8498,Scotland,1,21,2,3.0,9,5,2,1,...,21,1,12,6,4,17,2,59,3,0
39,10106,Bosnia and Herzegovina,1,14,2,3.0,8,4,1,0,...,14,0,21,10,6,71,1,79,3,0
40,10255,Egypt,1,25,2,2.0,14,3,8,0,...,25,1,28,12,3,18,3,57,2,0
35,8496,Czechia,1,12,1,0.0,7,3,0,0,...,12,2,9,6,4,21,4,38,0,0
17,6709,Ivory Coast,1,39,2,3.0,15,8,3,1,...,39,0,14,11,3,29,1,58,3,0
24,6719,Tunisia,1,10,0,1.0,6,3,1,0,...,10,6,21,6,4,13,1,51,1,0
28,7795,Saudi Arabia,1,10,1,1.0,7,3,1,0,...,10,0,11,9,6,43,9,40,1,0
27,6724,Paraguay,1,11,1,5.0,9,3,5,0,...,11,1,21,10,4,33,3,55,5,0
41,287981,Curacao,1,10,0,0.0,8,6,0,0,...,10,1,16,16,9,25,4,50,0,0
9,6316,South Africa,0,2,0,2.0,3,1,0,0,...,2,1,14,7,5,17,2,33,2,2
5,5888,Cape Verde,0,6,1,1.0,6,3,2,0,...,6,3,18,15,6,46,7,40,1,0
7,5934,Haiti,0,22,1,1.0,15,9,4,0,...,22,3,12,6,2,20,1,51,1,0
25,6720,Spain,0,51,2,1.0,27,12,8,1,...,51,2,13,6,2,7,1,40,1,0
10,6317,Algeria,0,14,0,0.0,7,4,3,0,...,14,1,17,8,0,12,3,43,0,0
13,6595,Turkiye,0,51,2,1.0,30,10,12,1,...,51,3,12,4,1,29,2,46,1,0
15,6707,Ecuador,0,16,1,1.0,12,8,3,3,...,16,0,21,13,1,18,3,44,1,0

In [7]:
# clean columns 467 (90%)
# fouls_home, accurate_passes_home, accurate_long_passes_home, accurate_crosses_home, ground_duels_won_home, aerial_won_home, dribbles_succeeded_home

df_to_clean = df[['homeTeamid', 'homeTeamName', 'awayTeamid', 'awayTeamName', 'fouls_home', 'fouls_away', 'accurate_passes_home', 'accurate_passes_away', 'accurate_long_passes_home', 'accurate_long_passes_away', 'accurate_crosses_home', 'accurate_crosses_away',
                       'ground_duels_won_home', 'ground_duels_won_away', 'aerial_won_home', 'aerial_won_away', 'dribbles_succeeded_home', 'dribbles_succeeded_away']]

df_to_clean

,homeTeamid,homeTeamName,awayTeamid,awayTeamName,fouls_home,fouls_away,accurate_passes_home,accurate_passes_away,accurate_long_passes_home,accurate_long_passes_away,accurate_crosses_home,accurate_crosses_away,ground_duels_won_home,ground_duels_won_away,aerial_won_home,aerial_won_away,dribbles_succeeded_home,dribbles_succeeded_away
0,6710,Mexico,6316,South Africa,467 (90%),272 (81%),467 (90%),272 (81%),31 (65%),17 (37%),4 (33%),1 (13%),32 (55%),26 (45%),15 (68%),7 (32%),9 (60%),1 (17%)
1,7804,South Korea,8496,Czechia,469 (87%),230 (70%),469 (87%),230 (70%),30 (49%),23 (33%),3 (25%),3 (20%),29 (57%),22 (43%),27 (63%),16 (37%),8 (57%),4 (57%)
2,5810,Canada,10106,Bosnia and Herzegovina,310 (74%),170 (63%),310 (74%),170 (63%),19 (44%),18 (29%),5 (21%),6 (60%),50 (58%),36 (42%),20 (32%),43 (68%),7 (47%),5 (23%)
3,6713,USA,6724,Paraguay,509 (85%),232 (73%),509 (85%),232 (73%),26 (54%),20 (34%),3 (16%),0 (0%),47 (55%),39 (45%),18 (53%),16 (47%),22 (63%),6 (60%)
4,5902,Qatar,6717,Switzerland,200 (72%),527 (91%),200 (72%),527 (91%),19 (30%),27 (77%),1 (11%),6 (17%),26 (49%),27 (51%),10 (50%),10 (50%),2 (50%),7 (54%)
5,8256,Brazil,6262,Morocco,449 (87%),419 (86%),449 (87%),419 (86%),18 (50%),17 (33%),4 (25%),2 (13%),41 (41%),58 (59%),12 (75%),4 (25%),5 (19%),16 (55%)
6,5934,Haiti,8498,Scotland,367 (85%),307 (82%),367 (85%),307 (82%),26 (44%),30 (52%),5 (22%),5 (36%),38 (50%),38 (50%),13 (38%),21 (62%),6 (43%),5 (38%)
7,6716,Australia,6595,Turkiye,201 (74%),635 (90%),201 (74%),635 (90%),16 (28%),19 (68%),4 (29%),2 (8%),27 (48%),29 (52%),15 (47%),17 (53%),8 (73%),5 (36%)
8,8570,Germany,287981,Curacao,554 (87%),282 (82%),554 (87%),282 (82%),12 (48%),17 (39%),5 (42%),2 (29%),38 (46%),45 (54%),9 (64%),5 (36%),9 (50%),12 (57%)
9,6708,Netherlands,6715,Japan,463 (88%),286 (84%),463 (88%),286 (84%),16 (46%),13 (36%),8 (38%),6 (26%),25 (54%),21 (46%),21 (75%),7 (25%),8 (53%),3 (33%)
10,6709,Ivory Coast,6707,Ecuador,397 (84%),419 (85%),397 (84%),419 (85%),18 (45%),11 (31%),2 (25%),4 (29%),41 (55%),33 (45%),17 (61%),11 (39%),14 (67%),3 (30%)
11,8520,Sweden,6719,Tunisia,278 (78%),292 (79%),278 (78%),292 (79%),22 (38%),24 (45%),3 (25%),3 (23%),26 (42%),36 (58%),15 (50%),15 (50%),5 (42%),7 (44%)
12,6720,Spain,5888,Cape Verde,734 (92%),205 (74%),734 (92%),205 (74%),24 (80%),19 (34%),6 (17%),1 (25%),21 (40%),31 (60%),19 (68%),9 (32%),7 (54%),4 (36%)
13,8263,Belgium,10255,Egypt,389 (86%),323 (81%),389 (86%),323 (81%),18 (60%),18 (35%),6 (38%),2 (15%),38 (44%),49 (56%),14 (64%),8 (36%),7 (37%),7 (54%)
14,7795,Saudi Arabia,5796,Uruguay,236 (73%),540 (88%),236 (73%),540 (88%),10 (24%),24 (59%),3 (50%),16 (34%),18 (45%),22 (55%),22 (52%),20 (48%),3 (60%),8 (67%)
15,6711,Iran,5820,New Zealand,314 (77%),376 (84%),314 (77%),376 (84%),27 (44%),21 (53%),6 (32%),1 (8%),29 (51%),28 (49%),25 (63%),15 (38%),4 (36%),6 (50%)
16,6723,France,6395,Senegal,505 (88%),427 (86%),505 (88%),427 (86%),21 (46%),25 (52%),0 (0%),1 (11%),31 (53%),27 (47%),12 (60%),8 (40%),5 (31%),8 (62%)
17,5819,Iraq,8492,Norway,271 (81%),477 (89%),271 (81%),477 (89%),22 (41%),18 (43%),6 (46%),7 (41%),42 (58%),31 (42%),10 (37%),17 (63%),10 (48%),5 (29%)
18,6706,Argentina,6317,Algeria,504 (90%),563 (92%),504 (90%),563 (92%),17 (53%),15 (60%),1 (17%),1 (11%),36 (49%),38 (51%),3 (38%),5 (63%),2 (22%),8 (35%)
19,8255,Austria,5816,Jordan,487 (84%),241 (73%),487 (84%),241 (73%),18 (38%),23 (44%),3 (18%),3 (20%),28 (42%),39 (58%),16 (64%),9 (36%),5 (36%),15 (63%)
20,8361,Portugal,6321,DR Congo,724 (92%),195 (78%),724 (92%),195 (78%),41 (64%),11 (28%),6 (26%),1 (10%),25 (42%),34 (58%),9 (53%),8 (47%),5 (42%),8 (53%)

In [26]:
# ✖️✖️✖️
# clean (%) with regex
# 👇 fixed code

cleaned_df = pd.DataFrame()

cleaned_df['fouls_home'] = df_to_clean['fouls_home'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['fouls_away'] = df_to_clean['fouls_away'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['accurate_passes_home'] = df_to_clean['accurate_passes_home'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['accurate_passes_away'] = df_to_clean['accurate_passes_away'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['accurate_long_passes_home'] = df_to_clean['accurate_long_passes_home'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['accurate_long_passes_away'] = df_to_clean['accurate_long_passes_away'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['accurate_crosses_home'] = df_to_clean['accurate_crosses_home'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['accurate_crosses_away'] = df_to_clean['accurate_crosses_away'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['ground_duels_won_home'] = df_to_clean['ground_duels_won_home'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['ground_duels_won_away'] = df_to_clean['ground_duels_won_away'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['aerial_won_home'] = df_to_clean['aerial_won_home'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['aerial_won_away'] = df_to_clean['aerial_won_away'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['dribbles_succeeded_home'] = df_to_clean['dribbles_succeeded_home'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['dribbles_succeeded_away'] = df_to_clean['dribbles_succeeded_away'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)

cleaned_df

,fouls_home,fouls_away,accurate_passes_home,accurate_passes_away,accurate_long_passes_home,accurate_long_passes_away,accurate_crosses_home,accurate_crosses_away,ground_duels_won_home,ground_duels_won_away,aerial_won_home,aerial_won_away,dribbles_succeeded_home,dribbles_succeeded_away
0,467,272,467,272,31,17,4,1,32,26,15,7,9,1
1,469,230,469,230,30,23,3,3,29,22,27,16,8,4
2,310,170,310,170,19,18,5,6,50,36,20,43,7,5
3,509,232,509,232,26,20,3,0,47,39,18,16,22,6
4,200,527,200,527,19,27,1,6,26,27,10,10,2,7
5,449,419,449,419,18,17,4,2,41,58,12,4,5,16
6,367,307,367,307,26,30,5,5,38,38,13,21,6,5
7,201,635,201,635,16,19,4,2,27,29,15,17,8,5
8,554,282,554,282,12,17,5,2,38,45,9,5,9,12
9,463,286,463,286,16,13,8,6,25,21,21,7,8,3
10,397,419,397,419,18,11,2,4,41,33,17,11,14,3
11,278,292,278,292,22,24,3,3,26,36,15,15,5,7
12,734,205,734,205,24,19,6,1,21,31,19,9,7,4
13,389,323,389,323,18,18,6,2,38,49,14,8,7,7
14,236,540,236,540,10,24,3,16,18,22,22,20,3,8
15,314,376,314,376,27,21,6,1,29,28,25,15,4,6
16,505,427,505,427,21,25,0,1,31,27,12,8,5,8

In [27]:
# ✖️✖️✖️
# clean (%) with regex
# loop with a mapping dictionary

columns_to_clean = [
    'fouls', 'accurate_passes', 'accurate_long_passes', 
    'accurate_crosses', 'ground_duels_won', 'aerial_won', 
    'dribbles_succeeded'
]

cleaned_df = pd.DataFrame()

for col in columns_to_clean:
    for suffix in ['home', 'away']:
        original_col = f'{col}_{suffix}'
        cleaned_df[original_col] = df_to_clean[original_col].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)

cleaned_df

,fouls_home,fouls_away,accurate_passes_home,accurate_passes_away,accurate_long_passes_home,accurate_long_passes_away,accurate_crosses_home,accurate_crosses_away,ground_duels_won_home,ground_duels_won_away,aerial_won_home,aerial_won_away,dribbles_succeeded_home,dribbles_succeeded_away
0,467,272,467,272,31,17,4,1,32,26,15,7,9,1
1,469,230,469,230,30,23,3,3,29,22,27,16,8,4
2,310,170,310,170,19,18,5,6,50,36,20,43,7,5
3,509,232,509,232,26,20,3,0,47,39,18,16,22,6
4,200,527,200,527,19,27,1,6,26,27,10,10,2,7
5,449,419,449,419,18,17,4,2,41,58,12,4,5,16
6,367,307,367,307,26,30,5,5,38,38,13,21,6,5
7,201,635,201,635,16,19,4,2,27,29,15,17,8,5
8,554,282,554,282,12,17,5,2,38,45,9,5,9,12
9,463,286,463,286,16,13,8,6,25,21,21,7,8,3
10,397,419,397,419,18,11,2,4,41,33,17,11,14,3
11,278,292,278,292,22,24,3,3,26,36,15,15,5,7
12,734,205,734,205,24,19,6,1,21,31,19,9,7,4
13,389,323,389,323,18,18,6,2,38,49,14,8,7,7
14,236,540,236,540,10,24,3,16,18,22,22,20,3,8
15,314,376,314,376,27,21,6,1,29,28,25,15,4,6
16,505,427,505,427,21,25,0,1,31,27,12,8,5,8

In [8]:
# ✔️✔️✔️ FINAL code for cleaning df

columns_to_clean = [
    'fouls', 'accurate_passes', 'accurate_long_passes', 
    'accurate_crosses', 'ground_duels_won', 'aerial_won', 
    'dribbles_succeeded'
]

cleaned_df = df_to_clean.copy()

for col in columns_to_clean:
    for suffix in ['home', 'away']:
        original_col = f'{col}_{suffix}'
        cleaned_df[original_col] = (
            cleaned_df[original_col]
            .str.replace(r'\s*\(.*\)', '', regex=True)
            .astype(int)
        )

cleaned_df

,homeTeamid,homeTeamName,awayTeamid,awayTeamName,fouls_home,fouls_away,accurate_passes_home,accurate_passes_away,accurate_long_passes_home,accurate_long_passes_away,accurate_crosses_home,accurate_crosses_away,ground_duels_won_home,ground_duels_won_away,aerial_won_home,aerial_won_away,dribbles_succeeded_home,dribbles_succeeded_away
0,6710,Mexico,6316,South Africa,467,272,467,272,31,17,4,1,32,26,15,7,9,1
1,7804,South Korea,8496,Czechia,469,230,469,230,30,23,3,3,29,22,27,16,8,4
2,5810,Canada,10106,Bosnia and Herzegovina,310,170,310,170,19,18,5,6,50,36,20,43,7,5
3,6713,USA,6724,Paraguay,509,232,509,232,26,20,3,0,47,39,18,16,22,6
4,5902,Qatar,6717,Switzerland,200,527,200,527,19,27,1,6,26,27,10,10,2,7
5,8256,Brazil,6262,Morocco,449,419,449,419,18,17,4,2,41,58,12,4,5,16
6,5934,Haiti,8498,Scotland,367,307,367,307,26,30,5,5,38,38,13,21,6,5
7,6716,Australia,6595,Turkiye,201,635,201,635,16,19,4,2,27,29,15,17,8,5
8,8570,Germany,287981,Curacao,554,282,554,282,12,17,5,2,38,45,9,5,9,12
9,6708,Netherlands,6715,Japan,463,286,463,286,16,13,8,6,25,21,21,7,8,3
10,6709,Ivory Coast,6707,Ecuador,397,419,397,419,18,11,2,4,41,33,17,11,14,3
11,8520,Sweden,6719,Tunisia,278,292,278,292,22,24,3,3,26,36,15,15,5,7
12,6720,Spain,5888,Cape Verde,734,205,734,205,24,19,6,1,21,31,19,9,7,4
13,8263,Belgium,10255,Egypt,389,323,389,323,18,18,6,2,38,49,14,8,7,7
14,7795,Saudi Arabia,5796,Uruguay,236,540,236,540,10,24,3,16,18,22,22,20,3,8
15,6711,Iran,5820,New Zealand,314,376,314,376,27,21,6,1,29,28,25,15,4,6
16,6723,France,6395,Senegal,505,427,505,427,21,25,0,1,31,27,12,8,5,8
17,5819,Iraq,8492,Norway,271,477,271,477,22,18,6,7,42,31,10,17,10,5
18,6706,Argentina,6317,Algeria,504,563,504,563,17,15,1,1,36,38,3,5,2,8
19,8255,Austria,5816,Jordan,487,241,487,241,18,23,3,3,28,39,16,9,5,15
20,8361,Portugal,6321,DR Congo,724,195,724,195,41,11,6,1,25,34,9,8,5,8

In [9]:
cleaned_df.columns

Index(['homeTeamid', 'homeTeamName', 'awayTeamid', 'awayTeamName',
       'fouls_home', 'fouls_away', 'accurate_passes_home',
       'accurate_passes_away', 'accurate_long_passes_home',
       'accurate_long_passes_away', 'accurate_crosses_home',
       'accurate_crosses_away', 'ground_duels_won_home',
       'ground_duels_won_away', 'aerial_won_home', 'aerial_won_away',
       'dribbles_succeeded_home', 'dribbles_succeeded_away'],
      dtype='str')

In [12]:
# SUM succeeded data
# fouls_home, accurate_passes_home, accurate_long_passes_home, accurate_crosses_home, ground_duels_won_home, aerial_won_home, dribbles_succeeded_home

# Create a dataframe with home teams data
succeed_home_df = cleaned_df[['homeTeamName', 'homeTeamid', 'fouls_home', 'accurate_passes_home', 'accurate_long_passes_home', 'accurate_crosses_home', 'ground_duels_won_home',
                      'aerial_won_home', 'dribbles_succeeded_home']].rename(
    columns={
        'homeTeamName': 'teamName',
        'homeTeamid': 'teamId',
        'fouls_home': 'fouls',
        'accurate_passes_home': 'accurate_passes',
        'accurate_long_passes_home': 'accurate_long_passes',
        'accurate_crosses_home': 'accurate_crosses',
        'ground_duels_won_home': 'ground_duels_won',
        'aerial_won_home': 'aerial_won',
        'dribbles_succeeded_home': 'dribbles_succeeded'        
    }
)

# Create a dataframe with away teams data
succeed_away_df = cleaned_df[['awayTeamName', 'awayTeamid', 'fouls_away', 'accurate_passes_away', 'accurate_long_passes_away', 'accurate_crosses_away', 'ground_duels_won_away',
                      'aerial_won_away', 'dribbles_succeeded_away']].rename(
    columns={
        'awayTeamName': 'teamName',
        'awayTeamid': 'teamId',
        'fouls_away': 'fouls',
        'accurate_passes_away': 'accurate_passes',
        'accurate_long_passes_away': 'accurate_long_passes',
        'accurate_crosses_away': 'accurate_crosses',
        'ground_duels_won_away': 'ground_duels_won',
        'aerial_won_away': 'aerial_won',
        'dribbles_succeeded_away': 'dribbles_succeeded'
    }
)

# Stack both dataframes together
succeed_sum_df = pd.concat([succeed_home_df, succeed_away_df], ignore_index=True)

succeed_df = (
    succeed_sum_df
    .groupby(['teamId', 'teamName'], as_index=False)[['fouls', 'accurate_passes', 'accurate_long_passes', 'accurate_crosses', 'ground_duels_won', 'aerial_won',
                                                      'dribbles_succeeded']]
    .sum()
    .sort_values('accurate_passes', ascending=False)
)

succeed_df

,teamId,teamName,fouls,accurate_passes,accurate_long_passes,accurate_crosses,ground_duels_won,aerial_won,dribbles_succeeded
25,6720,Spain,734,734,24,6,21,19,7
33,8361,Portugal,724,724,41,6,25,9,5
13,6595,Turkiye,635,635,19,2,29,17,5
10,6317,Algeria,563,563,15,1,38,5,8
38,8570,Germany,554,554,12,5,38,9,9
0,5796,Uruguay,540,540,24,16,22,20,8
23,6717,Switzerland,527,527,27,6,27,10,7
20,6713,USA,509,509,26,3,47,18,22
26,6723,France,505,505,21,0,31,12,5
14,6706,Argentina,504,504,17,1,36,3,2
30,8255,Austria,487,487,18,3,28,16,5
34,8492,Norway,477,477,18,7,31,17,5
29,7804,South Korea,469,469,30,3,29,27,8
18,6710,Mexico,467,467,31,4,32,15,9
16,6708,Netherlands,463,463,16,8,25,21,8
31,8256,Brazil,449,449,18,4,41,12,5
12,6395,Senegal,427,427,25,1,27,8,8
15,6707,Ecuador,419,419,11,4,33,11,3
8,6262,Morocco,419,419,17,2,58,4,16
17,6709,Ivory Coast,397,397,18,2,41,17,14
32,8263,Belgium,389,389,18,6,38,14,7
4,5820,New Zealand,376,376,21,1,28,15,6
7,5934,Haiti,367,367,26,5,38,13,6
40,10255,Egypt,323,323,18,2,49,8,7
19,6711,Iran,314,314,27,6,29,25,4
1,5810,Canada,310,310,19,5,50,20,7
36,8498,Scotland,307,307,30,5,38,21,5
24,6719,Tunisia,292,292,24,3,36,15,7
21,6715,Japan,286,286,13,6,21,7,3
41,287981,Curacao,282,282,17,2,45,5,12
37,8520,Sweden,278,278,22,3,26,15,5
9,6316,South Africa,272,272,17,1,26,7,1
3,5819,Iraq,271,271,22,6,42,10,10
2,5816,Jordan,241,241,23,3,39,9,15
28,7795,Saudi Arabia,236,236,10,3,18,22,3
27,6724,Paraguay,232,232,20,0,39,16,6
35,8496,Czechia,230,230,23,3,22,16,4
5,5888,Cape Verde,205,205,19,1,31,9,4
22,6716,Australia,201,201,16,4,27,15,8
6,5902,Qatar,200,200,19,1,26,10,2
11,6321,DR Congo,195,195,11,1,34,8,8
39,10106,Bosnia and Herzegovina,170,170,18,6,36,43,5

In [15]:
# JOIN sum_df & succeed_df

final_df = pd.merge(
    succeed_df,
    sum_df,
    on=['teamId', 'teamName'],
    how='inner'  # keeps only matching teamIds
)

final_df

,teamId,teamName,fouls,accurate_passes,accurate_long_passes,accurate_crosses,ground_duels_won,aerial_won,dribbles_succeeded,goals,...,touches_opp_box,offsides,tackles_won,interceptions,blocks,clearances,keeper_saves,duel_won,yellow_cards,red_cards
0,6720,Spain,734,734,24,6,21,19,7,0,...,51,2,13,6,2,7,1,40,1,0
1,8361,Portugal,724,724,41,6,25,9,5,1,...,29,3,12,3,2,10,1,34,3,0
2,6595,Turkiye,635,635,19,2,29,17,5,0,...,51,3,12,4,1,29,2,46,1,0
3,6317,Algeria,563,563,15,1,38,5,8,0,...,14,1,17,8,0,12,3,43,0,0
4,8570,Germany,554,554,12,5,38,9,9,7,...,63,0,19,12,0,8,1,47,0,0
5,5796,Uruguay,540,540,24,16,22,20,8,1,...,41,6,3,10,1,17,2,42,0,0
6,6717,Switzerland,527,527,27,6,27,10,7,1,...,42,1,8,7,0,13,3,37,1,0
7,6713,USA,509,509,26,3,47,18,22,4,...,53,2,9,9,3,15,0,65,1,0
8,6723,France,505,505,21,0,31,12,5,3,...,19,1,18,8,1,14,2,43,0,0
9,6706,Argentina,504,504,17,1,36,3,2,3,...,12,3,27,10,3,17,0,39,0,0
10,8255,Austria,487,487,18,3,28,16,5,3,...,28,3,17,15,2,24,3,44,1,0
11,8492,Norway,477,477,18,7,31,17,5,4,...,25,0,15,2,2,22,0,48,0,0
12,7804,South Korea,469,469,30,3,29,27,8,2,...,24,2,7,9,0,32,3,56,1,0
13,6710,Mexico,467,467,31,4,32,15,9,2,...,20,1,12,8,0,15,2,47,1,1
14,6708,Netherlands,463,463,16,8,25,21,8,2,...,33,1,11,7,0,23,1,46,3,0
15,8256,Brazil,449,449,18,4,41,12,5,1,...,22,0,23,5,6,23,2,53,2,0
16,6395,Senegal,427,427,25,1,27,8,8,1,...,14,3,14,8,2,17,5,35,0,0
17,6707,Ecuador,419,419,11,4,33,11,3,0,...,16,0,21,13,1,18,3,44,1,0
18,6262,Morocco,419,419,17,2,58,4,16,1,...,13,1,26,5,3,17,4,62,0,0
19,6709,Ivory Coast,397,397,18,2,41,17,14,1,...,39,0,14,11,3,29,1,58,3,0
20,8263,Belgium,389,389,18,6,38,14,7,1,...,30,0,16,10,8,26,2,52,2,0
21,5820,New Zealand,376,376,21,1,28,15,6,2,...,21,0,13,15,5,26,2,43,0,0
22,5934,Haiti,367,367,26,5,38,13,6,0,...,22,3,12,6,2,20,1,51,1,0
23,10255,Egypt,323,323,18,2,49,8,7,1,...,25,1,28,12,3,18,3,57,2,0
24,6711,Iran,314,314,27,6,29,25,4,2,...,25,2,17,11,1,27,6,54,1,0
25,5810,Canada,310,310,19,5,50,20,7,1,...,38,1,23,4,0,21,2,70,2,0
26,8498,Scotland,307,307,30,5,38,21,5,1,...,21,1,12,6,4,17,2,59,3,0
27,6719,Tunisia,292,292,24,3,36,15,7,1,...,10,6,21,6,4,13,1,51,1,0
28,6715,Japan,286,286,13,6,21,7,3,2,...,19,0,11,4,1,32,4,28,0,0
29,287981,Curacao,282,282,17,2,45,5,12,1,...,10,1,16,16,9,25,4,50,0,0
30,8520,Sweden,278,278,22,3,26,15,5,5,...,22,3,14,6,1,23,1,41,0,0
31,6316,South Africa,272,272,17,1,26,7,1,0,...,2,1,14,7,5,17,2,33,2,2
32,5819,Iraq,271,271,22,6,42,10,10,1,...,18,1,19,5,3,20,2,52,1,0
33,5816,Jordan,241,241,23,3,39,9,15,1,...,21,1,15,12,2,39,1,48,0,0
34,7795,Saudi Arabia,236,236,10,3,18,22,3,1,...,10,0,11,9,6,43,9,40,1,0
35,6724,Paraguay,232,232,20,0,39,16,6,1,...,11,1,21,10,4,33,3,55,5,0
36,8496,Czechia,230,230,23,3,22,16,4,1,...,12,2,9,6,4,21,4,38,0,0
37,5888,Cape Verde,205,205,19,1,31,9,4,0,...,6,3,18,15,6,46,7,40,1,0
38,6716,Australia,201,201,16,4,27,15,8,2,...,18,1,15,7,12,55,8,42,0,0
39,5902,Qatar,200,200,19,1,26,10,2,1,...,8,0,14,11,9,31,5,36,2,0
40,6321,DR Congo,195,195,11,1,34,8,8,1,...,10,2,17,5,2,27,0,42,1,0
41,10106,Bosnia and Herzegovina,170,170,18,6,36,43,5,1,...,14,0,21,10,6,71,1,79,3,0

In [34]:
# Sample data
e_df = pd.DataFrame({
    'values': ['467 (90%)', '123 (45%)', '999 (100%)', '50 (5%)']
})

e_df

       values
0   467 (90%)
1   123 (45%)
2  999 (100%)
3     50 (5%)