In [ ]:
import pandas as pd

In [3]:
df = pd.read_csv(r'C:\Users\Public\Documents\Axel\wcup26\matchStats\csv\fotmob_match_stats.csv')
df

,matchId,matchRound,homeTeamName,homeTeamid,awayTeamName,awayTeamid,home_goals,away_goals,ball_possession_home,ball_possession_away,...,ground_duels_won_home,ground_duels_won_away,aerial_won_home,aerial_won_away,dribbles_succeeded_home,dribbles_succeeded_away,yellow_cards_home,yellow_cards_away,red_cards_home,red_cards_away
0,4667751,1,Mexico,6710,South Africa,6316,2,0,60,40,...,32 (55%),26 (45%),15 (68%),7 (32%),9 (60%),1 (17%),1,2,1,2
1,4667752,1,South Korea,7804,Czechia,8496,2,1,62,38,...,29 (57%),22 (43%),27 (63%),16 (37%),8 (57%),4 (57%),1,0,0,0
2,4667757,1,Canada,5810,Bosnia and Herzegovina,10106,1,1,61,39,...,50 (58%),36 (42%),20 (32%),43 (68%),7 (47%),5 (23%),2,3,0,0
3,4667771,1,USA,6713,Paraguay,6724,4,1,65,35,...,47 (55%),39 (45%),18 (53%),16 (47%),22 (63%),6 (60%),1,5,0,0
4,4667758,1,Qatar,5902,Switzerland,6717,1,1,32,68,...,26 (49%),27 (51%),10 (50%),10 (50%),2 (50%),7 (54%),2,1,0,0
5,4667764,1,Brazil,8256,Morocco,6262,1,1,51,49,...,41 (41%),58 (59%),12 (75%),4 (25%),5 (19%),16 (55%),2,0,0,0
6,4667765,1,Haiti,5934,Scotland,8498,0,1,54,46,...,38 (50%),38 (50%),13 (38%),21 (62%),6 (43%),5 (38%),1,3,0,0
7,4667772,1,Australia,6716,Turkiye,6595,2,0,28,72,...,27 (48%),29 (52%),15 (47%),17 (53%),8 (73%),5 (36%),0,1,0,0
8,4667777,1,Germany,8570,Curacao,287981,7,1,65,35,...,38 (46%),45 (54%),9 (64%),5 (36%),9 (50%),12 (57%),0,0,0,0
9,4667783,1,Netherlands,6708,Japan,6715,2,2,60,40,...,25 (54%),21 (46%),21 (75%),7 (25%),8 (53%),3 (33%),3,0,0,0
10,4667778,1,Ivory Coast,6709,Ecuador,6707,1,0,48,52,...,41 (55%),33 (45%),17 (61%),11 (39%),14 (67%),3 (30%),3,1,0,0
11,4667784,1,Sweden,8520,Tunisia,6719,5,1,49,51,...,26 (42%),36 (58%),15 (50%),15 (50%),5 (42%),7 (44%),0,1,0,0
12,4667798,1,Spain,6720,Cape Verde,5888,0,0,74,26,...,21 (40%),31 (60%),19 (68%),9 (32%),7 (54%),4 (36%),1,1,0,0
13,4667790,1,Belgium,8263,Egypt,10255,1,1,54,46,...,38 (44%),49 (56%),14 (64%),8 (36%),7 (37%),7 (54%),2,2,0,0
14,4667799,1,Saudi Arabia,7795,Uruguay,5796,1,1,33,67,...,18 (45%),22 (55%),22 (52%),20 (48%),3 (60%),8 (67%),1,0,0,0
15,4667791,1,Iran,6711,New Zealand,5820,2,2,48,52,...,29 (51%),28 (49%),25 (63%),15 (38%),4 (36%),6 (50%),1,0,0,0
16,4667804,1,France,6723,Senegal,6395,3,1,54,46,...,31 (53%),27 (47%),12 (60%),8 (40%),5 (31%),8 (62%),0,0,0,0
17,4667805,1,Iraq,5819,Norway,8492,1,4,39,61,...,42 (58%),31 (42%),10 (37%),17 (63%),10 (48%),5 (29%),1,0,0,0
18,4667812,1,Argentina,6706,Algeria,6317,3,0,48,52,...,36 (49%),38 (51%),3 (38%),5 (63%),2 (22%),8 (35%),0,0,0,0
19,4667813,1,Austria,8255,Jordan,5816,3,1,63,37,...,28 (42%),39 (58%),16 (64%),9 (36%),5 (36%),15 (63%),1,0,0,0
20,4667819,1,Portugal,8361,DR Congo,6321,1,1,75,25,...,25 (42%),34 (58%),9 (53%),8 (47%),5 (42%),8 (53%),3,1,0,0
21,4667825,1,England,8491,Croatia,10155,4,2,52,48,...,28 (52%),26 (48%),12 (43%),16 (57%),7 (50%),5 (50%),0,0,0,0
22,4667826,1,Ghana,6714,Panama,5922,1,0,38,62,...,35 (44%),44 (56%),21 (62%),13 (38%),9 (38%),6 (43%),1,2,0,0
23,4667820,1,Uzbekistan,8700,Colombia,8258,1,3,39,61,...,24 (46%),28 (54%),10 (56%),8 (44%),5 (50%),5 (42%),1,1,0,0
24,4667753,2,Czechia,8496,South Africa,6316,1,1,38,62,...,32 (46%),38 (54%),13 (59%),9 (41%),10 (71%),8 (62%),1,2,0,0
25,4667759,2,Switzerland,6717,Bosnia and Herzegovina,10106,4,1,62,38,...,42 (62%),26 (38%),10 (45%),12 (55%),6 (50%),6 (50%),1,2,0,1
26,4667760,2,Canada,5810,Qatar,5902,6,0,79,21,...,25 (48%),27 (52%),8 (53%),7 (47%),6 (55%),2 (40%),1,1,0,2
27,4667754,2,Mexico,6710,South Korea,7804,1,0,42,58,...,27 (44%),34 (56%),15 (54%),13 (46%),6 (60%),9 (53%),0,2,0,0
28,4667774,2,USA,6713,Australia,6716,2,0,62,38,...,44 (54%),37 (46%),15 (36%),27 (64%),11 (65%),14 (56%),3,4,0,0
29,4667766,2,Scotland,8498,Morocco,6262,0,1,41,59,...,31 (55%),25 (45%),7 (44%),9 (56%),4 (67%),5 (28%),1,1,0,0
30,4667767,2,Brazil,8256,Haiti,5934,3,0,57,43,...,38 (54%),32 (46%),14 (58%),10 (42%),4 (27%),3 (18%),1,3,0,0
31,4667773,2,Turkiye,6595,Paraguay,6724,0,1,78,22,...,45 (46%),52 (54%),15 (43%),20 (57%),13 (48%),15 (60%),1,1,0,1
32,4667786,2,Netherlands,6708,Sweden,8520,5,1,51,49,...,29 (47%),33 (53%),14 (52%),13 (48%),3 (23%),7 (58%),0,3,0,0
33,4667780,2,Germany,8570,Ivory Coast,6709,2,1,59,41,...,37 (47%),41 (53%),8 (50%),8 (50%),5 (36%),17 (57%),0,0,0,0
34,4667779,2,Ecuador,6707,Curacao,287981,0,0,75,25,...,36 (52%),33 (48%),15 (44%),19 (56%),8 (62%),9 (43%),1,5,0,0
35,4667785,2,Tunisia,6719,Japan,6715,0,4,38,62,...,34 (54%),29 (46%),4 (22%),14 (78%),2 (29%),4 (27%),0,0,0,0
36,4667801,2,Spain,6720,Saudi Arabia,7795,4,0,67,33,...,18 (35%),33 (65%),11 (73%),4 (27%),7 (44%),8 (67%),0,2,0,0
37,4667793,2,Belgium,8263,Iran,6711,0,0,70,30,...,34 (57%),26 (43%),18 (51%),17 (49%),14 (67%),2 (40%),1,1,1,0
38,4667800,2,Uruguay,5796,Cape Verde,5888,2,2,65,35,...,27 (41%),39 (59%),20 (56%),16 (44%),7 (39%),12 (71%),2,2,0,0
39,4667792,2,New Zealand,5820,Egypt,10255,1,3,44,56,...,27 (44%),34 (56%),16 (44%),20 (56%),7 (47%),7 (58%),2,1,0,0
40,4667815,2,Argentina,6706,Austria,8255,2,0,54,46,...,39 (57%),30 (43%),11 (41%),16 (59%),6 (55%),6 (38%),2,2,0,0
41,4667807,2,France,6723,Iraq,5819,3,0,56,44,...,30 (50%),30 (50%),10 (56%),8 (44%),12 (60%),6 (55%),0,1,0,0
42,4667806,2,Norway,8492,Senegal,6395,3,2,42,58,...,18 (31%),40 (69%),20 (54%),17 (46%),5 (56%),11 (65%),0,0,0,0
43,4667814,2,Jordan,5816,Algeria,6317,1,2,28,72,...,42 (46%),49 (54%),18 (53%),16 (47%),7 (30%),14 (42%),1,1,0,0
44,4667822,2,Portugal,8361,Uzbekistan,8700,5,0,66,34,...,43 (52%),39 (48%),11 (65%),6 (35%),14 (54%),8 (53%),1,1,0,0
45,4667828,2,England,8491,Ghana,6714,0,0,79,21,...,43 (52%),39 (48%),18 (69%),8 (31%),7 (41%),4 (40%),1,1,0,0
46,4667827,2,Panama,5922,Croatia,10155,0,1,42,58,...,32 (40%),48 (60%),26 (63%),15 (37%),11 (58%),11 (100%),1,1,0,0
47,4667821,2,Colombia,8258,DR Congo,6321,1,0,64,36,...,28 (52%),26 (48%),19 (68%),9 (32%),3 (30%),0 (0%),2,1,0,0

In [4]:
df.columns

Index(['matchId', 'matchRound', 'homeTeamName', 'homeTeamid', 'awayTeamName',
       'awayTeamid', 'home_goals', 'away_goals', 'ball_possession_home',
       'ball_possession_away', 'big_chances_home', 'big_chances_away',
       'big_chances_missed_home', 'big_chances_missed_away', 'fouls_home',
       'fouls_away', 'corners_home', 'corners_away', 'total_shots_home',
       'total_shots_away', 'shots_off_target_home', 'shots_off_target_away',
       'shots_on_target_home', 'shots_on_target_away', 'blocked_shots_home',
       'blocked_shots_away', 'hit_woodwork_home', 'hit_woodwork_away',
       'shots_inside_box_home', 'shots_inside_box_away',
       'shots_outside_box_home', 'shots_outside_box_away', 'xG_home',
       'xG_away', 'xG_open_play_home', 'xG_open_play_away', 'xG_set_play_home',
       'xG_set_play_away', 'xG_non_penalty_home', 'xG_non_penalty_away',
       'xGOT_home', 'xGOT_away', 'passes_home', 'passes_away',
       'accurate_passes_home', 'accurate_passes_away', 'own_half_passes_home',
       'own_half_passes_away', 'opposition_half_passes_home',
       'opposition_half_passes_away', 'accurate_long_passes_home',
       'accurate_long_passes_away', 'accurate_crosses_home',
       'accurate_crosses_away', 'throws_home', 'throws_away',
       'touches_opp_box_home', 'touches_opp_box_away', 'offsides_home',
       'offsides_away', 'tackles_won_home', 'tackles_won_away',
       'interceptions_home', 'interceptions_away', 'blocks_home',
       'blocks_away', 'clearances_home', 'clearances_away',
       'keeper_saves_home', 'keeper_saves_away', 'duel_won_home',
       'duel_won_away', 'ground_duels_won_home', 'ground_duels_won_away',
       'aerial_won_home', 'aerial_won_away', 'dribbles_succeeded_home',
       'dribbles_succeeded_away', 'yellow_cards_home', 'yellow_cards_away',
       'red_cards_home', 'red_cards_away'],
      dtype='str')

In [5]:
# p90 minutes MEAN

# xG_home, xG_open_play_home, xG_set_play_home, xG_non_penalty_home, xGOT_home

# Create a dataframe with home teams data
xG_mean_home_df = df[['homeTeamName', 'homeTeamid', 'xG_home', 'xG_open_play_home', 'xG_set_play_home', 'xG_non_penalty_home', 'xGOT_home']].rename(
    columns={
        'homeTeamName': 'teamName',
        'homeTeamid': 'teamId',
        'xG_home': 'xG',
        'xG_open_play_home': 'xG_open_play',
        'xG_set_play_home': 'xG_set_play',
        'xG_non_penalty_home': 'xG_non_penalty',
        'xGOT_home': 'xGOT'
    }
)

# Create a dataframe with away teams data
xG_mean_away_df = df[['awayTeamName', 'awayTeamid', 'xG_away', 'xG_open_play_away', 'xG_set_play_away', 'xG_non_penalty_away', 'xGOT_away']].rename(
    columns={
        'awayTeamName': 'teamName',
        'awayTeamid': 'teamId',
        'xG_away': 'xG',
        'xG_open_play_away': 'xG_open_play',
        'xG_set_play_away': 'xG_set_play',
        'xG_non_penalty_away': 'xG_non_penalty',
        'xGOT_away': 'xGOT'
    }
)

# Stack both dataframes together
xG_mean_possession = pd.concat([xG_mean_home_df, xG_mean_away_df], ignore_index=True)

xG_mean_df = (
    xG_mean_possession
    .groupby(['teamId', 'teamName']).agg(
          matches=('teamName', 'size'),
          avg_xG=('xG', 'mean'),
          total_xG=('xG', 'sum'),
          avg_xG_open_play=('xG_open_play', 'mean'),
          avg_xG_set_play=('xG_set_play', 'mean'),
          avg_xG_non_penalty=('xG_non_penalty', 'mean')
      )
      .sort_values('avg_xG', ascending=False)
      .reset_index()
)

xG_mean_df

,teamId,teamName,matches,avg_xG,total_xG,avg_xG_open_play,avg_xG_set_play,avg_xG_non_penalty
0,8570,Germany,2,3.025,6.05,2.360,0.265,2.630
1,5810,Canada,2,2.925,5.85,2.380,0.540,2.925
2,6717,Switzerland,2,2.630,5.26,1.375,0.465,1.840
3,8492,Norway,2,2.360,4.72,1.985,0.375,2.360
4,8491,England,2,2.280,4.56,1.170,0.710,1.885
5,6723,France,2,2.280,4.56,2.230,0.995,2.335
6,6720,Spain,2,2.200,4.40,1.770,0.430,2.200
7,5796,Uruguay,2,2.020,4.04,1.425,0.595,2.020
8,6707,Ecuador,2,1.925,3.85,1.110,0.815,1.925
9,6706,Argentina,2,1.810,3.62,1.320,0.095,1.415
10,6595,Turkiye,2,1.765,3.53,1.455,0.310,1.765
11,6708,Netherlands,2,1.695,3.39,1.470,0.225,1.695
12,7804,South Korea,2,1.605,3.21,1.510,0.095,1.605
13,8263,Belgium,2,1.550,3.10,1.205,0.345,1.550
14,8361,Portugal,2,1.530,3.06,1.080,0.445,1.530
15,8256,Brazil,2,1.505,3.01,1.385,0.120,1.505
16,10255,Egypt,2,1.470,2.94,1.315,0.160,1.470
17,6709,Ivory Coast,2,1.375,2.75,1.325,0.050,1.375
18,6715,Japan,2,1.360,2.72,1.155,0.205,1.360
19,8258,Colombia,2,1.295,2.59,1.040,0.255,1.295
20,6713,USA,2,1.250,2.50,0.880,0.370,1.250
21,5820,New Zealand,2,1.240,2.48,0.525,0.710,1.240
22,6262,Morocco,2,1.180,2.36,1.100,0.080,1.180
23,10155,Croatia,2,1.175,2.35,0.955,0.215,1.175
24,8520,Sweden,2,1.170,2.34,0.905,0.265,1.170
25,6395,Senegal,2,1.110,2.22,0.870,0.485,0.915
26,8255,Austria,2,1.110,2.22,0.640,0.075,0.715
27,6317,Algeria,2,1.105,2.21,0.490,0.615,1.105
28,6711,Iran,2,1.060,2.12,0.745,0.310,1.060
29,6710,Mexico,2,0.995,1.99,0.835,0.160,0.995
30,8496,Czechia,2,0.925,1.85,0.350,0.575,0.925
31,8498,Scotland,2,0.780,1.56,0.710,0.070,0.780
32,6716,Australia,2,0.765,1.53,0.440,0.325,0.765
33,6714,Ghana,2,0.740,1.48,0.650,0.090,0.740
34,6316,South Africa,2,0.725,1.45,0.295,0.035,0.330
35,5819,Iraq,2,0.715,1.43,0.555,0.160,0.715
36,8700,Uzbekistan,2,0.705,1.41,0.675,0.030,0.705
37,5934,Haiti,2,0.640,1.28,0.560,0.085,0.640
38,5922,Panama,2,0.640,1.28,0.390,0.250,0.640
39,6321,DR Congo,2,0.620,1.24,0.260,0.355,0.620
40,10106,Bosnia and Herzegovina,2,0.605,1.21,0.070,0.540,0.605
41,5816,Jordan,2,0.545,1.09,0.355,0.195,0.545
42,5888,Cape Verde,2,0.540,1.08,0.360,0.180,0.540
43,287981,Curacao,2,0.455,0.91,0.365,0.090,0.455
44,6724,Paraguay,2,0.430,0.86,0.210,0.220,0.430
45,5902,Qatar,2,0.410,0.82,0.350,0.060,0.410
46,7795,Saudi Arabia,2,0.400,0.80,0.100,0.300,0.400
47,6719,Tunisia,2,0.165,0.33,0.025,0.140,0.165

In [6]:
# MEAN

# ball_possession_home

# Create a dataframe with home teams data
mean_home_df = df[['homeTeamName', 'homeTeamid', 'ball_possession_home']].rename(
    columns={
        'homeTeamName': 'teamName',
        'homeTeamid': 'teamId',
        'ball_possession_home': 'ball_possession'
    }
)

# Create a dataframe with away teams data
mean_away_df = df[['awayTeamName', 'awayTeamid', 'ball_possession_away']].rename(
    columns={
        'awayTeamName': 'teamName',
        'awayTeamid': 'teamId',
        'ball_possession_away': 'ball_possession'
    }
)

# Stack both dataframes together
mean_possession = pd.concat([mean_home_df, mean_away_df], ignore_index=True)

# Mean
ball_possession_df = (
    mean_possession
    .groupby(['teamId', 'teamName'], as_index=False)[['ball_possession']]
    .mean()
    .rename(columns={'ball_possession': 'mean_ball_possession'})
    .sort_values('mean_ball_possession', ascending=False)
)

ball_possession_df

    teamId                teamName  mean_ball_possession
14    6595                 Turkiye                  75.0
27    6720                   Spain                  70.5
36    8361                Portugal                  70.5
1     5810                  Canada                  70.0
0     5796                 Uruguay                  66.0
37    8491                 England                  65.5
25    6717             Switzerland                  65.0
16    6707                 Ecuador                  63.5
21    6713                     USA                  63.5
34    8258                Colombia                  62.5
35    8263                 Belgium                  62.0
11    6317                 Algeria                  62.0
42    8570                 Germany                  62.0
31    7804             South Korea                  60.0
17    6708             Netherlands                  55.5
28    6723                  France                  55.0
32    8255                 Austria                  54.5
33    8256                  Brazil                  54.0
9     6262                 Morocco                  54.0
45   10155                 Croatia                  53.0
13    6395                 Senegal                  52.0
7     5922                  Panama                  52.0
38    8492                  Norway                  51.5
19    6710                  Mexico                  51.0
15    6706               Argentina                  51.0
46   10255                   Egypt                  51.0
23    6715                   Japan                  51.0
10    6316            South Africa                  51.0
41    8520                  Sweden                  49.0
8     5934                   Haiti                  48.5
4     5820             New Zealand                  48.0
26    6719                 Tunisia                  44.5
18    6709             Ivory Coast                  44.5
40    8498                Scotland                  43.5
3     5819                    Iraq                  41.5
20    6711                    Iran                  39.0
44   10106  Bosnia and Herzegovina                  38.5
39    8496                 Czechia                  38.0
43    8700              Uzbekistan                  36.5
30    7795            Saudi Arabia                  33.0
24    6716               Australia                  33.0
2     5816                  Jordan                  32.5
5     5888              Cape Verde                  30.5
12    6321                DR Congo                  30.5
47  287981                 Curacao                  30.0
22    6714                   Ghana                  29.5
29    6724                Paraguay                  28.5
6     5902                   Qatar                  26.5

In [7]:
# Columns to SUM

# home_goals, big_chances_home, big_chances_missed_home, corners_home, total_shots_home, shots_off_target_home, blocked_shots_home, hit_woodwork_home, shots_inside_box_home, shots_outside_box_home,
# passes_home, own_half_passes_home, opposition_half_passes_home, throws_home, touches_opp_box_home, offsides_home, tackles_won_home, interceptions_home, blocks_home, clearances_home, keeper_saves_home,
# duel_won_home, yellow_cards_home, red_cards_home

# Create a dataframe with home teams data
home_df = df[['homeTeamName', 'homeTeamid', 'home_goals', 'big_chances_home', 'big_chances_missed_home', 'corners_home', 'total_shots_home', 'shots_off_target_home', 'blocked_shots_home',
              'hit_woodwork_home', 'shots_inside_box_home', 'shots_outside_box_home', 'passes_home', 'own_half_passes_home', 'opposition_half_passes_home', 'throws_home', 'touches_opp_box_home',
              'offsides_home', 'tackles_won_home', 'interceptions_home', 'blocks_home', 'clearances_home', 'keeper_saves_home', 'duel_won_home', 'yellow_cards_home', 'red_cards_home']].rename(
    columns={
        'homeTeamName': 'teamName',
        'homeTeamid': 'teamId',
        'home_goals': 'goals',
        'big_chances_home': 'big_chances',
        'big_chances_missed_home': 'big_chances_missed',
        'corners_home': 'corners',
        'total_shots_home': 'total_shots',
        'shots_off_target_home': 'shots_off_target',
        'blocked_shots_home': 'blocked_shots',
        'hit_woodwork_home': 'hit_woodwork',
        'shots_inside_box_home': 'shots_inside_box',
        'shots_outside_box_home': 'shots_outside_box',
        'passes_home': 'passes',
        'own_half_passes_home': 'own_half_passes',
        'opposition_half_passes_home': 'opposition_half_passes',
        'throws_home': 'throws',
        'touches_opp_box_home': 'touches_opp_box',
        'offsides_home': 'offsides',
        'tackles_won_home': 'tackles_won',
        'interceptions_home': 'interceptions',
        'blocks_home': 'blocks',
        'clearances_home': 'clearances',
        'keeper_saves_home': 'keeper_saves',
        'duel_won_home': 'duel_won',
        'yellow_cards_home': 'yellow_cards',
        'red_cards_home': 'red_cards'
    }
)

# Create a dataframe with away teams data
away_df = df[['awayTeamName', 'awayTeamid', 'away_goals', 'big_chances_away', 'big_chances_missed_away', 'corners_away', 'total_shots_away', 'shots_off_target_away', 'blocked_shots_away',
              'hit_woodwork_away', 'shots_inside_box_away', 'shots_outside_box_away', 'passes_away', 'own_half_passes_away', 'opposition_half_passes_away', 'throws_away', 'touches_opp_box_away',
              'offsides_away', 'tackles_won_away', 'interceptions_away', 'blocks_away', 'clearances_away', 'keeper_saves_away', 'duel_won_away', 'yellow_cards_away', 'red_cards_away']].rename(
    columns={
        'awayTeamName': 'teamName',
        'awayTeamid': 'teamId',
        'away_goals': 'goals',
        'big_chances_away': 'big_chances',
        'big_chances_missed_away': 'big_chances_missed',
        'corners_away': 'corners',
        'total_shots_away': 'total_shots',
        'shots_off_target_away': 'shots_off_target',
        'blocked_shots_away': 'blocked_shots',
        'hit_woodwork_away': 'hit_woodwork',
        'shots_inside_box_away': 'shots_inside_box',
        'shots_outside_box_away': 'shots_outside_box',
        'passes_away': 'passes',
        'own_half_passes_away': 'own_half_passes',
        'opposition_half_passes_away': 'opposition_half_passes',
        'throws_away': 'throws',
        'touches_opp_box_away': 'touches_opp_box',
        'offsides_away': 'offsides',
        'tackles_won_away': 'tackles_won',
        'interceptions_away': 'interceptions',
        'blocks_away': 'blocks',
        'clearances_away': 'clearances',
        'keeper_saves_away': 'keeper_saves',
        'duel_won_away': 'duel_won',
        'yellow_cards_away': 'yellow_cards',
        'red_cards_away': 'red_cards'
    }
)

# Stack both dataframes together
teams_goals = pd.concat([home_df, away_df], ignore_index=True)

# Sum
sum_df = (
    teams_goals
    .groupby(['teamId', 'teamName'], as_index=False)[['goals', 'big_chances', 'big_chances_missed', 'corners', 'total_shots', 'shots_off_target', 'blocked_shots', 'hit_woodwork', 'shots_inside_box',
                                                      'shots_outside_box', 'passes', 'own_half_passes', 'opposition_half_passes', 'throws', 'touches_opp_box', 'offsides', 'tackles_won', 'interceptions',
                                                      'blocks', 'clearances', 'keeper_saves', 'duel_won', 'yellow_cards', 'red_cards']]
    .sum()
    .sort_values('goals', ascending=False)
)

sum_df

,teamId,teamName,goals,big_chances,big_chances_missed,corners,total_shots,shots_off_target,blocked_shots,hit_woodwork,...,touches_opp_box,offsides,tackles_won,interceptions,blocks,clearances,keeper_saves,duel_won,yellow_cards,red_cards
42,8570,Germany,9,95,12,0.0,42,11,12,1,...,95,0,45,19,5,24,2,92,0,0
1,5810,Canada,7,135,8,3.0,45,13,18,1,...,135,2,32,10,1,24,2,103,3,0
17,6708,Netherlands,7,53,3,3.0,20,5,2,0,...,53,4,26,15,2,47,8,89,3,0
38,8492,Norway,7,49,10,0.0,25,7,6,1,...,49,0,25,10,7,48,2,86,0,0
21,6713,USA,6,73,6,4.0,26,8,10,0,...,73,3,29,29,3,46,2,124,4,0
23,6715,Japan,6,36,4,0.0,21,9,4,0,...,36,1,29,11,2,57,4,71,0,0
41,8520,Sweden,6,48,6,3.0,29,8,6,0,...,48,6,32,11,2,37,3,87,3,0
36,8361,Portugal,6,65,7,4.0,24,9,5,0,...,65,5,26,8,5,26,3,88,4,0
28,6723,France,6,60,9,0.0,30,11,6,1,...,60,2,32,13,2,23,2,83,0,0
15,6706,Argentina,5,31,4,2.0,22,8,3,0,...,31,5,48,18,3,52,1,89,2,0
25,6717,Switzerland,5,77,10,2.0,39,13,12,0,...,77,4,27,12,1,30,5,89,2,0
27,6720,Spain,4,88,7,1.0,49,24,10,2,...,88,4,23,19,3,24,2,69,1,0
37,8491,England,4,70,9,1.0,41,16,11,1,...,70,2,23,8,3,22,3,101,1,0
46,10255,Egypt,4,61,5,3.0,33,9,14,0,...,61,1,44,18,6,55,7,111,3,0
33,8256,Brazil,4,46,6,3.0,20,6,4,0,...,46,8,44,15,7,37,5,105,3,0
34,8258,Colombia,4,51,6,3.0,35,12,10,2,...,51,10,20,16,4,38,2,83,3,0
45,10155,Croatia,3,31,5,1.0,16,6,3,0,...,31,3,30,14,7,55,8,105,1,0
4,5820,New Zealand,3,38,5,2.0,25,7,5,0,...,38,3,25,19,11,48,6,86,2,0
19,6710,Mexico,3,26,4,1.0,24,10,6,1,...,26,4,26,14,3,35,4,89,1,1
13,6395,Senegal,3,40,5,0.0,22,10,6,1,...,40,7,30,18,5,35,8,92,0,0
0,5796,Uruguay,3,75,4,2.0,44,18,14,2,...,75,9,19,17,5,28,4,89,2,0
32,8255,Austria,3,46,5,3.0,17,11,1,0,...,46,3,29,24,7,39,5,90,3,0
44,10106,Bosnia and Herzegovina,2,22,2,5.0,13,5,2,0,...,22,1,34,21,9,107,4,117,5,1
20,6711,Iran,2,40,3,2.0,24,11,6,1,...,40,6,36,23,7,78,13,97,2,0
2,5816,Jordan,2,34,1,1.0,19,9,2,1,...,34,2,45,15,7,75,7,108,1,0
5,5888,Cape Verde,2,16,2,3.0,18,7,6,0,...,16,3,34,28,13,94,7,95,3,0
9,6262,Morocco,2,39,5,1.0,26,11,10,1,...,39,1,36,10,6,31,4,96,1,0
39,8496,Czechia,2,28,4,1.0,21,11,3,0,...,28,4,21,15,11,43,7,83,1,0
24,6716,Australia,2,38,1,4.0,14,7,1,0,...,38,1,28,13,18,79,9,106,4,0
18,6709,Ivory Coast,2,60,4,3.0,24,10,8,1,...,60,1,34,24,7,55,6,107,3,0
29,6724,Paraguay,2,23,1,6.0,16,6,7,0,...,23,4,46,19,16,81,8,127,6,1
11,6317,Algeria,2,44,3,1.0,24,8,8,0,...,44,1,42,19,0,27,6,108,1,0
31,7804,South Korea,2,35,7,3.0,24,9,7,0,...,35,8,24,14,1,44,6,103,3,0
35,8263,Belgium,1,72,3,3.0,38,17,11,1,...,72,3,28,13,9,37,5,104,3,1
22,6714,Ghana,1,24,2,2.0,10,4,3,0,...,24,6,38,16,8,67,7,103,2,0
30,7795,Saudi Arabia,1,12,1,3.0,10,4,2,0,...,12,3,26,22,8,78,14,77,3,0
6,5902,Qatar,1,9,1,3.0,8,4,1,0,...,9,1,30,21,23,92,9,70,3,2
3,5819,Iraq,1,25,2,2.0,15,11,3,0,...,25,1,35,15,7,48,4,90,2,0
12,6321,DR Congo,1,20,1,2.0,15,7,5,0,...,20,2,32,12,8,46,8,77,2,0
10,6316,South Africa,1,22,1,4.0,20,6,8,0,...,22,4,34,16,8,41,4,80,4,2
43,8700,Uzbekistan,1,11,1,2.0,15,6,5,2,...,11,2,28,21,7,53,5,79,2,0
40,8498,Scotland,1,41,3,4.0,15,8,5,1,...,41,2,32,15,8,34,3,97,4,0
47,287981,Curacao,1,22,0,5.0,18,10,3,0,...,22,3,33,24,11,57,19,102,5,0
26,6719,Tunisia,1,18,0,1.0,8,4,2,0,...,18,7,39,20,7,36,2,89,1,0
14,6595,Turkiye,0,101,7,2.0,62,25,24,2,...,101,5,29,10,3,58,3,106,2,0
8,5934,Haiti,0,39,1,4.0,22,12,5,0,...,39,7,28,15,3,42,3,93,4,0
7,5922,Panama,0,38,3,3.0,19,10,4,0,...,38,2,39,10,3,46,3,115,3,0
16,6707,Ecuador,0,59,7,2.0,39,18,5,4,...,59,1,40,20,3,35,6,95,2,0

In [8]:
# clean columns 467 (90%)
# fouls_home, accurate_passes_home, accurate_long_passes_home, accurate_crosses_home, ground_duels_won_home, aerial_won_home, dribbles_succeeded_home

df_to_clean = df[['homeTeamid', 'homeTeamName', 'awayTeamid', 'awayTeamName', 'fouls_home', 'fouls_away', 'accurate_passes_home', 'accurate_passes_away', 'accurate_long_passes_home', 'accurate_long_passes_away', 'accurate_crosses_home', 'accurate_crosses_away',
                       'ground_duels_won_home', 'ground_duels_won_away', 'aerial_won_home', 'aerial_won_away', 'dribbles_succeeded_home', 'dribbles_succeeded_away']]

df_to_clean

,homeTeamid,homeTeamName,awayTeamid,awayTeamName,fouls_home,fouls_away,accurate_passes_home,accurate_passes_away,accurate_long_passes_home,accurate_long_passes_away,accurate_crosses_home,accurate_crosses_away,ground_duels_won_home,ground_duels_won_away,aerial_won_home,aerial_won_away,dribbles_succeeded_home,dribbles_succeeded_away
0,6710,Mexico,6316,South Africa,467 (90%),272 (81%),467 (90%),272 (81%),31 (65%),17 (37%),4 (33%),1 (13%),32 (55%),26 (45%),15 (68%),7 (32%),9 (60%),1 (17%)
1,7804,South Korea,8496,Czechia,469 (87%),230 (70%),469 (87%),230 (70%),30 (49%),23 (33%),3 (25%),3 (20%),29 (57%),22 (43%),27 (63%),16 (37%),8 (57%),4 (57%)
2,5810,Canada,10106,Bosnia and Herzegovina,310 (74%),170 (63%),310 (74%),170 (63%),19 (44%),18 (29%),5 (21%),6 (60%),50 (58%),36 (42%),20 (32%),43 (68%),7 (47%),5 (23%)
3,6713,USA,6724,Paraguay,509 (85%),232 (73%),509 (85%),232 (73%),26 (54%),20 (34%),3 (16%),0 (0%),47 (55%),39 (45%),18 (53%),16 (47%),22 (63%),6 (60%)
4,5902,Qatar,6717,Switzerland,200 (72%),527 (91%),200 (72%),527 (91%),19 (30%),27 (77%),1 (11%),6 (17%),26 (49%),27 (51%),10 (50%),10 (50%),2 (50%),7 (54%)
5,8256,Brazil,6262,Morocco,449 (87%),419 (86%),449 (87%),419 (86%),18 (50%),17 (33%),4 (25%),2 (13%),41 (41%),58 (59%),12 (75%),4 (25%),5 (19%),16 (55%)
6,5934,Haiti,8498,Scotland,367 (85%),307 (82%),367 (85%),307 (82%),26 (44%),30 (52%),5 (22%),5 (36%),38 (50%),38 (50%),13 (38%),21 (62%),6 (43%),5 (38%)
7,6716,Australia,6595,Turkiye,201 (74%),635 (90%),201 (74%),635 (90%),16 (28%),19 (68%),4 (29%),2 (8%),27 (48%),29 (52%),15 (47%),17 (53%),8 (73%),5 (36%)
8,8570,Germany,287981,Curacao,554 (87%),282 (82%),554 (87%),282 (82%),12 (48%),17 (39%),5 (42%),2 (29%),38 (46%),45 (54%),9 (64%),5 (36%),9 (50%),12 (57%)
9,6708,Netherlands,6715,Japan,463 (88%),286 (84%),463 (88%),286 (84%),16 (46%),13 (36%),8 (38%),6 (26%),25 (54%),21 (46%),21 (75%),7 (25%),8 (53%),3 (33%)
10,6709,Ivory Coast,6707,Ecuador,397 (84%),419 (85%),397 (84%),419 (85%),18 (45%),11 (31%),2 (25%),4 (29%),41 (55%),33 (45%),17 (61%),11 (39%),14 (67%),3 (30%)
11,8520,Sweden,6719,Tunisia,278 (78%),292 (79%),278 (78%),292 (79%),22 (38%),24 (45%),3 (25%),3 (23%),26 (42%),36 (58%),15 (50%),15 (50%),5 (42%),7 (44%)
12,6720,Spain,5888,Cape Verde,734 (92%),205 (74%),734 (92%),205 (74%),24 (80%),19 (34%),6 (17%),1 (25%),21 (40%),31 (60%),19 (68%),9 (32%),7 (54%),4 (36%)
13,8263,Belgium,10255,Egypt,389 (86%),323 (81%),389 (86%),323 (81%),18 (60%),18 (35%),6 (38%),2 (15%),38 (44%),49 (56%),14 (64%),8 (36%),7 (37%),7 (54%)
14,7795,Saudi Arabia,5796,Uruguay,236 (73%),540 (88%),236 (73%),540 (88%),10 (24%),24 (59%),3 (50%),16 (34%),18 (45%),22 (55%),22 (52%),20 (48%),3 (60%),8 (67%)
15,6711,Iran,5820,New Zealand,314 (77%),376 (84%),314 (77%),376 (84%),27 (44%),21 (53%),6 (32%),1 (8%),29 (51%),28 (49%),25 (63%),15 (38%),4 (36%),6 (50%)
16,6723,France,6395,Senegal,505 (88%),427 (86%),505 (88%),427 (86%),21 (46%),25 (52%),0 (0%),1 (11%),31 (53%),27 (47%),12 (60%),8 (40%),5 (31%),8 (62%)
17,5819,Iraq,8492,Norway,271 (81%),477 (89%),271 (81%),477 (89%),22 (41%),18 (43%),6 (46%),7 (41%),42 (58%),31 (42%),10 (37%),17 (63%),10 (48%),5 (29%)
18,6706,Argentina,6317,Algeria,504 (90%),563 (92%),504 (90%),563 (92%),17 (53%),15 (60%),1 (17%),1 (11%),36 (49%),38 (51%),3 (38%),5 (63%),2 (22%),8 (35%)
19,8255,Austria,5816,Jordan,487 (84%),241 (73%),487 (84%),241 (73%),18 (38%),23 (44%),3 (18%),3 (20%),28 (42%),39 (58%),16 (64%),9 (36%),5 (36%),15 (63%)
20,8361,Portugal,6321,DR Congo,724 (92%),195 (78%),724 (92%),195 (78%),41 (64%),11 (28%),6 (26%),1 (10%),25 (42%),34 (58%),9 (53%),8 (47%),5 (42%),8 (53%)
21,8491,England,10155,Croatia,406 (86%),381 (86%),406 (86%),381 (86%),15 (37%),18 (43%),6 (46%),2 (15%),28 (52%),26 (48%),12 (43%),16 (57%),7 (50%),5 (50%)
22,6714,Ghana,5922,Panama,292 (83%),503 (86%),292 (83%),503 (86%),30 (58%),34 (49%),4 (25%),4 (19%),35 (44%),44 (56%),21 (62%),13 (38%),9 (38%),6 (43%)
23,8700,Uzbekistan,8258,Colombia,243 (76%),444 (86%),243 (76%),444 (86%),17 (32%),17 (35%),3 (23%),6 (38%),24 (46%),28 (54%),10 (56%),8 (44%),5 (50%),5 (42%)
24,8496,Czechia,6316,South Africa,272 (80%),508 (90%),272 (80%),508 (90%),22 (49%),30 (52%),7 (44%),4 (24%),32 (46%),38 (54%),13 (59%),9 (41%),10 (71%),8 (62%)
25,6717,Switzerland,10106,Bosnia and Herzegovina,516 (88%),287 (81%),516 (88%),287 (81%),25 (50%),13 (27%),1 (4%),0 (0%),42 (62%),26 (38%),10 (45%),12 (55%),6 (50%),6 (50%)
26,5810,Canada,5902,Qatar,515 (91%),104 (64%),515 (91%),104 (64%),10 (63%),17 (31%),13 (24%),1 (33%),25 (48%),27 (52%),8 (53%),7 (47%),6 (55%),2 (40%)
27,6710,Mexico,7804,South Korea,349 (82%),488 (84%),349 (82%),488 (84%),16 (29%),23 (36%),4 (67%),5 (56%),27 (44%),34 (56%),15 (54%),13 (46%),6 (60%),9 (53%)
28,6713,USA,6716,Australia,444 (85%),219 (71%),444 (85%),219 (71%),26 (44%),19 (41%),4 (29%),4 (21%),44 (54%),37 (46%),15 (36%),27 (64%),11 (65%),14 (56%)
29,8498,Scotland,6262,Morocco,388 (85%),600 (90%),388 (85%),600 (90%),20 (43%),14 (32%),3 (23%),2 (20%),31 (55%),25 (45%),7 (44%),9 (56%),4 (67%),5 (28%)
30,8256,Brazil,5934,Haiti,462 (88%),332 (83%),462 (88%),332 (83%),20 (45%),31 (55%),1 (11%),3 (27%),38 (54%),32 (46%),14 (58%),10 (42%),4 (27%),3 (18%)
31,6595,Turkiye,6724,Paraguay,559 (89%),96 (54%),559 (89%),96 (54%),28 (67%),22 (34%),8 (19%),2 (33%),45 (46%),52 (54%),15 (43%),20 (57%),13 (48%),15 (60%)
32,6708,Netherlands,8520,Sweden,398 (89%),361 (85%),398 (89%),361 (85%),18 (51%),6 (20%),3 (19%),3 (14%),29 (47%),33 (53%),14 (52%),13 (48%),3 (23%),7 (58%)
33,8570,Germany,6709,Ivory Coast,554 (89%),367 (85%),554 (89%),367 (85%),17 (57%),29 (50%),5 (24%),5 (56%),37 (47%),41 (53%),8 (50%),8 (50%),5 (36%),17 (57%)
34,6707,Ecuador,287981,Curacao,581 (90%),159 (70%),581 (90%),159 (70%),14 (41%),15 (30%),11 (33%),1 (100%),36 (52%),33 (48%),15 (44%),19 (56%),8 (62%),9 (43%)
35,6719,Tunisia,6715,Japan,284 (80%),521 (89%),284 (80%),521 (89%),16 (29%),18 (56%),2 (20%),2 (18%),34 (54%),29 (46%),4 (22%),14 (78%),2 (29%),4 (27%)
36,6720,Spain,7795,Saudi Arabia,668 (92%),294 (81%),668 (92%),294 (81%),28 (74%),14 (40%),7 (28%),0 (0%),18 (35%),33 (65%),11 (73%),4 (27%),7 (44%),8 (67%)
37,8263,Belgium,6711,Iran,533 (86%),198 (73%),533 (86%),198 (73%),12 (34%),18 (36%),6 (19%),2 (25%),34 (57%),26 (43%),18 (51%),17 (49%),14 (67%),2 (40%)
38,5796,Uruguay,5888,Cape Verde,420 (82%),205 (74%),420 (82%),205 (74%),23 (48%),18 (30%),4 (14%),2 (29%),27 (41%),39 (59%),20 (56%),16 (44%),7 (39%),12 (71%)
39,5820,New Zealand,10255,Egypt,337 (80%),460 (87%),337 (80%),460 (87%),20 (40%),22 (46%),3 (20%),7 (32%),27 (44%),34 (56%),16 (44%),20 (56%),7 (47%),7 (58%)
40,6706,Argentina,8255,Austria,494 (89%),401 (86%),494 (89%),401 (86%),12 (44%),11 (52%),1 (25%),3 (18%),39 (57%),30 (43%),11 (41%),16 (59%),6 (55%),6 (38%)
41,6723,France,5819,Iraq,540 (90%),413 (86%),540 (90%),413 (86%),17 (57%),21 (41%),2 (14%),4 (44%),30 (50%),30 (50%),10 (56%),8 (44%),12 (60%),6 (55%)
42,8492,Norway,6395,Senegal,282 (80%),430 (88%),282 (80%),430 (88%),25 (49%),37 (64%),3 (30%),8 (35%),18 (31%),40 (69%),20 (54%),17 (46%),5 (56%),11 (65%)
43,5816,Jordan,6317,Algeria,181 (72%),561 (88%),181 (72%),561 (88%),23 (43%),19 (43%),2 (40%),5 (24%),42 (46%),49 (54%),18 (53%),16 (47%),7 (30%),14 (42%)
44,8361,Portugal,8700,Uzbekistan,562 (90%),262 (81%),562 (90%),262 (81%),23 (55%),9 (31%),5 (23%),0 (0%),43 (52%),39 (48%),11 (65%),6 (35%),14 (54%),8 (53%)
45,8491,England,6714,Ghana,586 (93%),127 (74%),586 (93%),127 (74%),14 (54%),24 (42%),7 (23%),0 (0%),43 (52%),39 (48%),18 (69%),8 (31%),7 (41%),4 (40%)
46,5922,Panama,10155,Croatia,277 (79%),432 (84%),277 (79%),432 (84%),25 (46%),19 (37%),6 (19%),5 (28%),32 (40%),48 (60%),26 (63%),15 (37%),11 (58%),11 (100%)
47,8258,Colombia,6321,DR Congo,473 (87%),226 (76%),473 (87%),226 (76%),40 (61%),14 (29%),3 (25%),4 (29%),28 (52%),26 (48%),19 (68%),9 (32%),3 (30%),0 (0%)

In [26]:
# ✖️✖️✖️
# clean (%) with regex
# 👇 fixed code

cleaned_df = pd.DataFrame()

cleaned_df['fouls_home'] = df_to_clean['fouls_home'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['fouls_away'] = df_to_clean['fouls_away'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['accurate_passes_home'] = df_to_clean['accurate_passes_home'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['accurate_passes_away'] = df_to_clean['accurate_passes_away'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['accurate_long_passes_home'] = df_to_clean['accurate_long_passes_home'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['accurate_long_passes_away'] = df_to_clean['accurate_long_passes_away'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['accurate_crosses_home'] = df_to_clean['accurate_crosses_home'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['accurate_crosses_away'] = df_to_clean['accurate_crosses_away'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['ground_duels_won_home'] = df_to_clean['ground_duels_won_home'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['ground_duels_won_away'] = df_to_clean['ground_duels_won_away'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['aerial_won_home'] = df_to_clean['aerial_won_home'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['aerial_won_away'] = df_to_clean['aerial_won_away'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['dribbles_succeeded_home'] = df_to_clean['dribbles_succeeded_home'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['dribbles_succeeded_away'] = df_to_clean['dribbles_succeeded_away'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)

cleaned_df

,fouls_home,fouls_away,accurate_passes_home,accurate_passes_away,accurate_long_passes_home,accurate_long_passes_away,accurate_crosses_home,accurate_crosses_away,ground_duels_won_home,ground_duels_won_away,aerial_won_home,aerial_won_away,dribbles_succeeded_home,dribbles_succeeded_away
0,467,272,467,272,31,17,4,1,32,26,15,7,9,1
1,469,230,469,230,30,23,3,3,29,22,27,16,8,4
2,310,170,310,170,19,18,5,6,50,36,20,43,7,5
3,509,232,509,232,26,20,3,0,47,39,18,16,22,6
4,200,527,200,527,19,27,1,6,26,27,10,10,2,7
5,449,419,449,419,18,17,4,2,41,58,12,4,5,16
6,367,307,367,307,26,30,5,5,38,38,13,21,6,5
7,201,635,201,635,16,19,4,2,27,29,15,17,8,5
8,554,282,554,282,12,17,5,2,38,45,9,5,9,12
9,463,286,463,286,16,13,8,6,25,21,21,7,8,3
10,397,419,397,419,18,11,2,4,41,33,17,11,14,3
11,278,292,278,292,22,24,3,3,26,36,15,15,5,7
12,734,205,734,205,24,19,6,1,21,31,19,9,7,4
13,389,323,389,323,18,18,6,2,38,49,14,8,7,7
14,236,540,236,540,10,24,3,16,18,22,22,20,3,8
15,314,376,314,376,27,21,6,1,29,28,25,15,4,6
16,505,427,505,427,21,25,0,1,31,27,12,8,5,8

In [27]:
# ✖️✖️✖️
# clean (%) with regex
# loop with a mapping dictionary

columns_to_clean = [
    'fouls', 'accurate_passes', 'accurate_long_passes', 
    'accurate_crosses', 'ground_duels_won', 'aerial_won', 
    'dribbles_succeeded'
]

cleaned_df = pd.DataFrame()

for col in columns_to_clean:
    for suffix in ['home', 'away']:
        original_col = f'{col}_{suffix}'
        cleaned_df[original_col] = df_to_clean[original_col].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)

cleaned_df

,fouls_home,fouls_away,accurate_passes_home,accurate_passes_away,accurate_long_passes_home,accurate_long_passes_away,accurate_crosses_home,accurate_crosses_away,ground_duels_won_home,ground_duels_won_away,aerial_won_home,aerial_won_away,dribbles_succeeded_home,dribbles_succeeded_away
0,467,272,467,272,31,17,4,1,32,26,15,7,9,1
1,469,230,469,230,30,23,3,3,29,22,27,16,8,4
2,310,170,310,170,19,18,5,6,50,36,20,43,7,5
3,509,232,509,232,26,20,3,0,47,39,18,16,22,6
4,200,527,200,527,19,27,1,6,26,27,10,10,2,7
5,449,419,449,419,18,17,4,2,41,58,12,4,5,16
6,367,307,367,307,26,30,5,5,38,38,13,21,6,5
7,201,635,201,635,16,19,4,2,27,29,15,17,8,5
8,554,282,554,282,12,17,5,2,38,45,9,5,9,12
9,463,286,463,286,16,13,8,6,25,21,21,7,8,3
10,397,419,397,419,18,11,2,4,41,33,17,11,14,3
11,278,292,278,292,22,24,3,3,26,36,15,15,5,7
12,734,205,734,205,24,19,6,1,21,31,19,9,7,4
13,389,323,389,323,18,18,6,2,38,49,14,8,7,7
14,236,540,236,540,10,24,3,16,18,22,22,20,3,8
15,314,376,314,376,27,21,6,1,29,28,25,15,4,6
16,505,427,505,427,21,25,0,1,31,27,12,8,5,8

In [9]:
# ✔️✔️✔️ FINAL code for cleaning df

columns_to_clean = [
    'fouls', 'accurate_passes', 'accurate_long_passes', 
    'accurate_crosses', 'ground_duels_won', 'aerial_won', 
    'dribbles_succeeded'
]

cleaned_df = df_to_clean.copy()

for col in columns_to_clean:
    for suffix in ['home', 'away']:
        original_col = f'{col}_{suffix}'
        cleaned_df[original_col] = (
            cleaned_df[original_col]
            .str.replace(r'\s*\(.*\)', '', regex=True)
            .astype(int)
        )

cleaned_df

,homeTeamid,homeTeamName,awayTeamid,awayTeamName,fouls_home,fouls_away,accurate_passes_home,accurate_passes_away,accurate_long_passes_home,accurate_long_passes_away,accurate_crosses_home,accurate_crosses_away,ground_duels_won_home,ground_duels_won_away,aerial_won_home,aerial_won_away,dribbles_succeeded_home,dribbles_succeeded_away
0,6710,Mexico,6316,South Africa,467,272,467,272,31,17,4,1,32,26,15,7,9,1
1,7804,South Korea,8496,Czechia,469,230,469,230,30,23,3,3,29,22,27,16,8,4
2,5810,Canada,10106,Bosnia and Herzegovina,310,170,310,170,19,18,5,6,50,36,20,43,7,5
3,6713,USA,6724,Paraguay,509,232,509,232,26,20,3,0,47,39,18,16,22,6
4,5902,Qatar,6717,Switzerland,200,527,200,527,19,27,1,6,26,27,10,10,2,7
5,8256,Brazil,6262,Morocco,449,419,449,419,18,17,4,2,41,58,12,4,5,16
6,5934,Haiti,8498,Scotland,367,307,367,307,26,30,5,5,38,38,13,21,6,5
7,6716,Australia,6595,Turkiye,201,635,201,635,16,19,4,2,27,29,15,17,8,5
8,8570,Germany,287981,Curacao,554,282,554,282,12,17,5,2,38,45,9,5,9,12
9,6708,Netherlands,6715,Japan,463,286,463,286,16,13,8,6,25,21,21,7,8,3
10,6709,Ivory Coast,6707,Ecuador,397,419,397,419,18,11,2,4,41,33,17,11,14,3
11,8520,Sweden,6719,Tunisia,278,292,278,292,22,24,3,3,26,36,15,15,5,7
12,6720,Spain,5888,Cape Verde,734,205,734,205,24,19,6,1,21,31,19,9,7,4
13,8263,Belgium,10255,Egypt,389,323,389,323,18,18,6,2,38,49,14,8,7,7
14,7795,Saudi Arabia,5796,Uruguay,236,540,236,540,10,24,3,16,18,22,22,20,3,8
15,6711,Iran,5820,New Zealand,314,376,314,376,27,21,6,1,29,28,25,15,4,6
16,6723,France,6395,Senegal,505,427,505,427,21,25,0,1,31,27,12,8,5,8
17,5819,Iraq,8492,Norway,271,477,271,477,22,18,6,7,42,31,10,17,10,5
18,6706,Argentina,6317,Algeria,504,563,504,563,17,15,1,1,36,38,3,5,2,8
19,8255,Austria,5816,Jordan,487,241,487,241,18,23,3,3,28,39,16,9,5,15
20,8361,Portugal,6321,DR Congo,724,195,724,195,41,11,6,1,25,34,9,8,5,8
21,8491,England,10155,Croatia,406,381,406,381,15,18,6,2,28,26,12,16,7,5
22,6714,Ghana,5922,Panama,292,503,292,503,30,34,4,4,35,44,21,13,9,6
23,8700,Uzbekistan,8258,Colombia,243,444,243,444,17,17,3,6,24,28,10,8,5,5
24,8496,Czechia,6316,South Africa,272,508,272,508,22,30,7,4,32,38,13,9,10,8
25,6717,Switzerland,10106,Bosnia and Herzegovina,516,287,516,287,25,13,1,0,42,26,10,12,6,6
26,5810,Canada,5902,Qatar,515,104,515,104,10,17,13,1,25,27,8,7,6,2
27,6710,Mexico,7804,South Korea,349,488,349,488,16,23,4,5,27,34,15,13,6,9
28,6713,USA,6716,Australia,444,219,444,219,26,19,4,4,44,37,15,27,11,14
29,8498,Scotland,6262,Morocco,388,600,388,600,20,14,3,2,31,25,7,9,4,5
30,8256,Brazil,5934,Haiti,462,332,462,332,20,31,1,3,38,32,14,10,4,3
31,6595,Turkiye,6724,Paraguay,559,96,559,96,28,22,8,2,45,52,15,20,13,15
32,6708,Netherlands,8520,Sweden,398,361,398,361,18,6,3,3,29,33,14,13,3,7
33,8570,Germany,6709,Ivory Coast,554,367,554,367,17,29,5,5,37,41,8,8,5,17
34,6707,Ecuador,287981,Curacao,581,159,581,159,14,15,11,1,36,33,15,19,8,9
35,6719,Tunisia,6715,Japan,284,521,284,521,16,18,2,2,34,29,4,14,2,4
36,6720,Spain,7795,Saudi Arabia,668,294,668,294,28,14,7,0,18,33,11,4,7,8
37,8263,Belgium,6711,Iran,533,198,533,198,12,18,6,2,34,26,18,17,14,2
38,5796,Uruguay,5888,Cape Verde,420,205,420,205,23,18,4,2,27,39,20,16,7,12
39,5820,New Zealand,10255,Egypt,337,460,337,460,20,22,3,7,27,34,16,20,7,7
40,6706,Argentina,8255,Austria,494,401,494,401,12,11,1,3,39,30,11,16,6,6
41,6723,France,5819,Iraq,540,413,540,413,17,21,2,4,30,30,10,8,12,6
42,8492,Norway,6395,Senegal,282,430,282,430,25,37,3,8,18,40,20,17,5,11
43,5816,Jordan,6317,Algeria,181,561,181,561,23,19,2,5,42,49,18,16,7,14
44,8361,Portugal,8700,Uzbekistan,562,262,562,262,23,9,5,0,43,39,11,6,14,8
45,8491,England,6714,Ghana,586,127,586,127,14,24,7,0,43,39,18,8,7,4
46,5922,Panama,10155,Croatia,277,432,277,432,25,19,6,5,32,48,26,15,11,11
47,8258,Colombia,6321,DR Congo,473,226,473,226,40,14,3,4,28,26,19,9,3,0

In [10]:
# SUM succeeded data
# fouls_home, accurate_passes_home, accurate_long_passes_home, accurate_crosses_home, ground_duels_won_home, aerial_won_home, dribbles_succeeded_home

# Create a dataframe with home teams data
succeed_home_df = cleaned_df[['homeTeamName', 'homeTeamid', 'fouls_home', 'accurate_passes_home', 'accurate_long_passes_home', 'accurate_crosses_home', 'ground_duels_won_home',
                      'aerial_won_home', 'dribbles_succeeded_home']].rename(
    columns={
        'homeTeamName': 'teamName',
        'homeTeamid': 'teamId',
        'fouls_home': 'fouls',
        'accurate_passes_home': 'accurate_passes',
        'accurate_long_passes_home': 'accurate_long_passes',
        'accurate_crosses_home': 'accurate_crosses',
        'ground_duels_won_home': 'ground_duels_won',
        'aerial_won_home': 'aerial_won',
        'dribbles_succeeded_home': 'dribbles_succeeded'        
    }
)

# Create a dataframe with away teams data
succeed_away_df = cleaned_df[['awayTeamName', 'awayTeamid', 'fouls_away', 'accurate_passes_away', 'accurate_long_passes_away', 'accurate_crosses_away', 'ground_duels_won_away',
                      'aerial_won_away', 'dribbles_succeeded_away']].rename(
    columns={
        'awayTeamName': 'teamName',
        'awayTeamid': 'teamId',
        'fouls_away': 'fouls',
        'accurate_passes_away': 'accurate_passes',
        'accurate_long_passes_away': 'accurate_long_passes',
        'accurate_crosses_away': 'accurate_crosses',
        'ground_duels_won_away': 'ground_duels_won',
        'aerial_won_away': 'aerial_won',
        'dribbles_succeeded_away': 'dribbles_succeeded'
    }
)

# Stack both dataframes together
succeed_sum_df = pd.concat([succeed_home_df, succeed_away_df], ignore_index=True)

succeed_df = (
    succeed_sum_df
    .groupby(['teamId', 'teamName'], as_index=False)[['fouls', 'accurate_passes', 'accurate_long_passes', 'accurate_crosses', 'ground_duels_won', 'aerial_won',
                                                      'dribbles_succeeded']]
    .sum()
    .sort_values('accurate_passes', ascending=False)
)

succeed_df

,teamId,teamName,fouls,accurate_passes,accurate_long_passes,accurate_crosses,ground_duels_won,aerial_won,dribbles_succeeded
27,6720,Spain,1402,1402,52,13,39,30,14
36,8361,Portugal,1286,1286,64,11,68,20,19
14,6595,Turkiye,1194,1194,47,10,74,32,18
11,6317,Algeria,1124,1124,34,6,87,21,22
42,8570,Germany,1108,1108,29,10,75,17,14
28,6723,France,1045,1045,38,2,61,22,17
25,6717,Switzerland,1043,1043,52,7,69,20,13
9,6262,Morocco,1019,1019,31,4,83,13,21
16,6707,Ecuador,1000,1000,25,15,69,26,11
15,6706,Argentina,998,998,29,2,75,14,8
37,8491,England,992,992,29,13,71,30,14
0,5796,Uruguay,960,960,47,20,49,40,15
31,7804,South Korea,957,957,53,8,63,40,17
21,6713,USA,953,953,52,7,91,33,33
35,8263,Belgium,922,922,30,12,72,32,21
34,8258,Colombia,917,917,57,9,56,27,8
33,8256,Brazil,911,911,38,5,79,26,9
32,8255,Austria,888,888,29,6,58,32,11
17,6708,Netherlands,861,861,34,11,54,35,11
13,6395,Senegal,857,857,62,9,67,25,19
1,5810,Canada,825,825,29,18,75,28,13
19,6710,Mexico,816,816,47,8,59,30,15
45,10155,Croatia,813,813,37,7,74,31,16
23,6715,Japan,807,807,31,8,50,21,7
46,10255,Egypt,783,783,40,9,83,28,14
7,5922,Panama,780,780,59,10,76,39,17
10,6316,South Africa,780,780,47,5,64,16,9
18,6709,Ivory Coast,764,764,47,7,82,25,31
38,8492,Norway,759,759,43,10,49,37,10
4,5820,New Zealand,713,713,41,4,55,31,13
8,5934,Haiti,699,699,57,8,70,23,9
40,8498,Scotland,695,695,50,8,69,28,9
3,5819,Iraq,684,684,43,10,72,18,16
41,8520,Sweden,639,639,28,6,59,28,12
26,6719,Tunisia,576,576,40,5,70,19,9
30,7795,Saudi Arabia,530,530,24,3,51,26,11
20,6711,Iran,512,512,45,8,55,42,6
43,8700,Uzbekistan,505,505,26,3,63,16,13
39,8496,Czechia,502,502,45,10,54,29,14
44,10106,Bosnia and Herzegovina,457,457,31,6,62,55,11
47,287981,Curacao,441,441,32,3,78,24,21
2,5816,Jordan,422,422,46,5,81,27,22
12,6321,DR Congo,421,421,25,5,60,17,8
24,6716,Australia,420,420,35,8,64,42,22
22,6714,Ghana,419,419,54,4,74,29,13
5,5888,Cape Verde,410,410,37,3,70,25,16
29,6724,Paraguay,328,328,42,2,91,36,21
6,5902,Qatar,304,304,36,2,53,17,4

In [11]:
# JOIN sum_df & succeed_df

final_df = pd.merge(
    succeed_df,
    sum_df,
    on=['teamId', 'teamName'],
    how='inner'  # keeps only matching teamIds
)

final_df.head()

,teamId,teamName,fouls,accurate_passes,accurate_long_passes,accurate_crosses,ground_duels_won,aerial_won,dribbles_succeeded,goals,...,touches_opp_box,offsides,tackles_won,interceptions,blocks,clearances,keeper_saves,duel_won,yellow_cards,red_cards
0,6720,Spain,1402,1402,52,13,39,30,14,4,...,88,4,23,19,3,24,2,69,1,0
1,8361,Portugal,1286,1286,64,11,68,20,19,6,...,65,5,26,8,5,26,3,88,4,0
2,6595,Turkiye,1194,1194,47,10,74,32,18,0,...,101,5,29,10,3,58,3,106,2,0
3,6317,Algeria,1124,1124,34,6,87,21,22,2,...,44,1,42,19,0,27,6,108,1,0
4,8570,Germany,1108,1108,29,10,75,17,14,9,...,95,0,45,19,5,24,2,92,0,0

In [12]:
# JOIN the 4 data frames

join_df = (
    xG_mean_df
    .merge(ball_possession_df, on=['teamId', 'teamName'], how='inner')
    .merge(final_df, on=['teamId', 'teamName'], how='inner')
)

join_df

,teamId,teamName,matches,avg_xG,total_xG,avg_xG_open_play,avg_xG_set_play,avg_xG_non_penalty,mean_ball_possession,fouls,...,touches_opp_box,offsides,tackles_won,interceptions,blocks,clearances,keeper_saves,duel_won,yellow_cards,red_cards
0,8570,Germany,2,3.025,6.05,2.360,0.265,2.630,62.0,1108,...,95,0,45,19,5,24,2,92,0,0
1,5810,Canada,2,2.925,5.85,2.380,0.540,2.925,70.0,825,...,135,2,32,10,1,24,2,103,3,0
2,6717,Switzerland,2,2.630,5.26,1.375,0.465,1.840,65.0,1043,...,77,4,27,12,1,30,5,89,2,0
3,8492,Norway,2,2.360,4.72,1.985,0.375,2.360,51.5,759,...,49,0,25,10,7,48,2,86,0,0
4,8491,England,2,2.280,4.56,1.170,0.710,1.885,65.5,992,...,70,2,23,8,3,22,3,101,1,0
5,6723,France,2,2.280,4.56,2.230,0.995,2.335,55.0,1045,...,60,2,32,13,2,23,2,83,0,0
6,6720,Spain,2,2.200,4.40,1.770,0.430,2.200,70.5,1402,...,88,4,23,19,3,24,2,69,1,0
7,5796,Uruguay,2,2.020,4.04,1.425,0.595,2.020,66.0,960,...,75,9,19,17,5,28,4,89,2,0
8,6707,Ecuador,2,1.925,3.85,1.110,0.815,1.925,63.5,1000,...,59,1,40,20,3,35,6,95,2,0
9,6706,Argentina,2,1.810,3.62,1.320,0.095,1.415,51.0,998,...,31,5,48,18,3,52,1,89,2,0
10,6595,Turkiye,2,1.765,3.53,1.455,0.310,1.765,75.0,1194,...,101,5,29,10,3,58,3,106,2,0
11,6708,Netherlands,2,1.695,3.39,1.470,0.225,1.695,55.5,861,...,53,4,26,15,2,47,8,89,3,0
12,7804,South Korea,2,1.605,3.21,1.510,0.095,1.605,60.0,957,...,35,8,24,14,1,44,6,103,3,0
13,8263,Belgium,2,1.550,3.10,1.205,0.345,1.550,62.0,922,...,72,3,28,13,9,37,5,104,3,1
14,8361,Portugal,2,1.530,3.06,1.080,0.445,1.530,70.5,1286,...,65,5,26,8,5,26,3,88,4,0
15,8256,Brazil,2,1.505,3.01,1.385,0.120,1.505,54.0,911,...,46,8,44,15,7,37,5,105,3,0
16,10255,Egypt,2,1.470,2.94,1.315,0.160,1.470,51.0,783,...,61,1,44,18,6,55,7,111,3,0
17,6709,Ivory Coast,2,1.375,2.75,1.325,0.050,1.375,44.5,764,...,60,1,34,24,7,55,6,107,3,0
18,6715,Japan,2,1.360,2.72,1.155,0.205,1.360,51.0,807,...,36,1,29,11,2,57,4,71,0,0
19,8258,Colombia,2,1.295,2.59,1.040,0.255,1.295,62.5,917,...,51,10,20,16,4,38,2,83,3,0
20,6713,USA,2,1.250,2.50,0.880,0.370,1.250,63.5,953,...,73,3,29,29,3,46,2,124,4,0
21,5820,New Zealand,2,1.240,2.48,0.525,0.710,1.240,48.0,713,...,38,3,25,19,11,48,6,86,2,0
22,6262,Morocco,2,1.180,2.36,1.100,0.080,1.180,54.0,1019,...,39,1,36,10,6,31,4,96,1,0
23,10155,Croatia,2,1.175,2.35,0.955,0.215,1.175,53.0,813,...,31,3,30,14,7,55,8,105,1,0
24,8520,Sweden,2,1.170,2.34,0.905,0.265,1.170,49.0,639,...,48,6,32,11,2,37,3,87,3,0
25,6395,Senegal,2,1.110,2.22,0.870,0.485,0.915,52.0,857,...,40,7,30,18,5,35,8,92,0,0
26,8255,Austria,2,1.110,2.22,0.640,0.075,0.715,54.5,888,...,46,3,29,24,7,39,5,90,3,0
27,6317,Algeria,2,1.105,2.21,0.490,0.615,1.105,62.0,1124,...,44,1,42,19,0,27,6,108,1,0
28,6711,Iran,2,1.060,2.12,0.745,0.310,1.060,39.0,512,...,40,6,36,23,7,78,13,97,2,0
29,6710,Mexico,2,0.995,1.99,0.835,0.160,0.995,51.0,816,...,26,4,26,14,3,35,4,89,1,1
30,8496,Czechia,2,0.925,1.85,0.350,0.575,0.925,38.0,502,...,28,4,21,15,11,43,7,83,1,0
31,8498,Scotland,2,0.780,1.56,0.710,0.070,0.780,43.5,695,...,41,2,32,15,8,34,3,97,4,0
32,6716,Australia,2,0.765,1.53,0.440,0.325,0.765,33.0,420,...,38,1,28,13,18,79,9,106,4,0
33,6714,Ghana,2,0.740,1.48,0.650,0.090,0.740,29.5,419,...,24,6,38,16,8,67,7,103,2,0
34,6316,South Africa,2,0.725,1.45,0.295,0.035,0.330,51.0,780,...,22,4,34,16,8,41,4,80,4,2
35,5819,Iraq,2,0.715,1.43,0.555,0.160,0.715,41.5,684,...,25,1,35,15,7,48,4,90,2,0
36,8700,Uzbekistan,2,0.705,1.41,0.675,0.030,0.705,36.5,505,...,11,2,28,21,7,53,5,79,2,0
37,5934,Haiti,2,0.640,1.28,0.560,0.085,0.640,48.5,699,...,39,7,28,15,3,42,3,93,4,0
38,5922,Panama,2,0.640,1.28,0.390,0.250,0.640,52.0,780,...,38,2,39,10,3,46,3,115,3,0
39,6321,DR Congo,2,0.620,1.24,0.260,0.355,0.620,30.5,421,...,20,2,32,12,8,46,8,77,2,0
40,10106,Bosnia and Herzegovina,2,0.605,1.21,0.070,0.540,0.605,38.5,457,...,22,1,34,21,9,107,4,117,5,1
41,5816,Jordan,2,0.545,1.09,0.355,0.195,0.545,32.5,422,...,34,2,45,15,7,75,7,108,1,0
42,5888,Cape Verde,2,0.540,1.08,0.360,0.180,0.540,30.5,410,...,16,3,34,28,13,94,7,95,3,0
43,287981,Curacao,2,0.455,0.91,0.365,0.090,0.455,30.0,441,...,22,3,33,24,11,57,19,102,5,0
44,6724,Paraguay,2,0.430,0.86,0.210,0.220,0.430,28.5,328,...,23,4,46,19,16,81,8,127,6,1
45,5902,Qatar,2,0.410,0.82,0.350,0.060,0.410,26.5,304,...,9,1,30,21,23,92,9,70,3,2
46,7795,Saudi Arabia,2,0.400,0.80,0.100,0.300,0.400,33.0,530,...,12,3,26,22,8,78,14,77,3,0
47,6719,Tunisia,2,0.165,0.33,0.025,0.140,0.165,44.5,576,...,18,7,39,20,7,36,2,89,1,0

In [13]:
join_df.columns

Index(['teamId', 'teamName', 'matches', 'avg_xG', 'total_xG',
       'avg_xG_open_play', 'avg_xG_set_play', 'avg_xG_non_penalty',
       'mean_ball_possession', 'fouls', 'accurate_passes',
       'accurate_long_passes', 'accurate_crosses', 'ground_duels_won',
       'aerial_won', 'dribbles_succeeded', 'goals', 'big_chances',
       'big_chances_missed', 'corners', 'total_shots', 'shots_off_target',
       'blocked_shots', 'hit_woodwork', 'shots_inside_box',
       'shots_outside_box', 'passes', 'own_half_passes',
       'opposition_half_passes', 'throws', 'touches_opp_box', 'offsides',
       'tackles_won', 'interceptions', 'blocks', 'clearances', 'keeper_saves',
       'duel_won', 'yellow_cards', 'red_cards'],
      dtype='str')

In [14]:
# SAVE variable in CSV
join_df.to_csv(r'C:\Users\Public\Documents\Axel\wcup26\data\clean_fotmob_match_stats.csv', index=False)

In [34]:
# Sample data
e_df = pd.DataFrame({
    'values': ['467 (90%)', '123 (45%)', '999 (100%)', '50 (5%)']
})

e_df

       values
0   467 (90%)
1   123 (45%)
2  999 (100%)
3     50 (5%)