In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\Public\Documents\Axel\wcup26\matchStats\csv\fotmob_match_stats.csv')
df

,matchId,matchRound,homeTeamName,homeTeamid,awayTeamName,awayTeamid,home_goals,away_goals,ball_possession_home,ball_possession_away,...,ground_duels_won_home,ground_duels_won_away,aerial_won_home,aerial_won_away,dribbles_succeeded_home,dribbles_succeeded_away,yellow_cards_home,yellow_cards_away,red_cards_home,red_cards_away
0,4667751,1,Mexico,6710,South Africa,6316,2,0,60,40,...,32 (55%),26 (45%),15 (68%),7 (32%),9 (60%),1 (17%),1,2,1,2
1,4667752,1,South Korea,7804,Czechia,8496,2,1,62,38,...,29 (57%),22 (43%),27 (63%),16 (37%),8 (57%),4 (57%),1,0,0,0
2,4667757,1,Canada,5810,Bosnia and Herzegovina,10106,1,1,61,39,...,50 (58%),36 (42%),20 (32%),43 (68%),7 (47%),5 (23%),2,3,0,0
3,4667771,1,USA,6713,Paraguay,6724,4,1,65,35,...,47 (55%),39 (45%),18 (53%),16 (47%),22 (63%),6 (60%),1,5,0,0
4,4667758,1,Qatar,5902,Switzerland,6717,1,1,32,68,...,26 (49%),27 (51%),10 (50%),10 (50%),2 (50%),7 (54%),2,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,4653854,1/4,Argentina,6706,Switzerland,6717,3,1,59,41,...,42 (58%),30 (42%),20 (59%),14 (41%),12 (75%),5 (36%),3,0,0,1
100,4653855,1/2,France,6723,Spain,6720,0,2,49,51,...,36 (51%),35 (49%),8 (32%),17 (68%),11 (46%),2 (40%),2,1,0,0
101,4653856,1/2,England,8491,Argentina,6706,1,2,36,64,...,37 (46%),43 (54%),13 (59%),9 (41%),7 (37%),13 (81%),1,3,0,0
102,4653857,bronze,France,6723,England,8491,4,6,46,54,...,31 (33%),64 (67%),8 (62%),5 (38%),7 (37%),23 (85%),0,0,0,0
103,4653858,final,Spain,6720,Argentina,6706,1,0,65,35,...,51 (52%),48 (48%),13 (52%),12 (48%),14 (56%),9 (64%),0,4,0,1

In [3]:
df.columns

Index(['matchId', 'matchRound', 'homeTeamName', 'homeTeamid', 'awayTeamName',
       'awayTeamid', 'home_goals', 'away_goals', 'ball_possession_home',
       'ball_possession_away', 'big_chances_home', 'big_chances_away',
       'big_chances_missed_home', 'big_chances_missed_away', 'fouls_home',
       'fouls_away', 'corners_home', 'corners_away', 'total_shots_home',
       'total_shots_away', 'shots_off_target_home', 'shots_off_target_away',
       'shots_on_target_home', 'shots_on_target_away', 'blocked_shots_home',
       'blocked_shots_away', 'hit_woodwork_home', 'hit_woodwork_away',
       'shots_inside_box_home', 'shots_inside_box_away',
       'shots_outside_box_home', 'shots_outside_box_away', 'xG_home',
       'xG_away', 'xG_open_play_home', 'xG_open_play_away', 'xG_set_play_home',
       'xG_set_play_away', 'xG_non_penalty_home', 'xG_non_penalty_away',
       'xGOT_home', 'xGOT_away', 'passes_home', 'passes_away',
       'accurate_passes_home', 'accurate_passes_away', 'own_half_passes_home',
       'own_half_passes_away', 'opposition_half_passes_home',
       'opposition_half_passes_away', 'accurate_long_passes_home',
       'accurate_long_passes_away', 'accurate_crosses_home',
       'accurate_crosses_away', 'throws_home', 'throws_away',
       'touches_opp_box_home', 'touches_opp_box_away', 'offsides_home',
       'offsides_away', 'tackles_won_home', 'tackles_won_away',
       'interceptions_home', 'interceptions_away', 'blocks_home',
       'blocks_away', 'clearances_home', 'clearances_away',
       'keeper_saves_home', 'keeper_saves_away', 'duel_won_home',
       'duel_won_away', 'ground_duels_won_home', 'ground_duels_won_away',
       'aerial_won_home', 'aerial_won_away', 'dribbles_succeeded_home',
       'dribbles_succeeded_away', 'yellow_cards_home', 'yellow_cards_away',
       'red_cards_home', 'red_cards_away'],
      dtype='str')

In [4]:
# p90 minutes MEAN

# xG_home, xG_open_play_home, xG_set_play_home, xG_non_penalty_home, xGOT_home

# Create a dataframe with home teams data
xG_mean_home_df = df[['homeTeamName', 'homeTeamid', 'xG_home', 'xG_open_play_home', 'xG_set_play_home', 'xG_non_penalty_home', 'xGOT_home']].rename(
    columns={
        'homeTeamName': 'teamName',
        'homeTeamid': 'teamId',
        'xG_home': 'xG',
        'xG_open_play_home': 'xG_open_play',
        'xG_set_play_home': 'xG_set_play',
        'xG_non_penalty_home': 'xG_non_penalty',
        'xGOT_home': 'xGOT'
    }
)

# Create a dataframe with away teams data
xG_mean_away_df = df[['awayTeamName', 'awayTeamid', 'xG_away', 'xG_open_play_away', 'xG_set_play_away', 'xG_non_penalty_away', 'xGOT_away']].rename(
    columns={
        'awayTeamName': 'teamName',
        'awayTeamid': 'teamId',
        'xG_away': 'xG',
        'xG_open_play_away': 'xG_open_play',
        'xG_set_play_away': 'xG_set_play',
        'xG_non_penalty_away': 'xG_non_penalty',
        'xGOT_away': 'xGOT'
    }
)

# Stack both dataframes together
xG_mean_possession = pd.concat([xG_mean_home_df, xG_mean_away_df], ignore_index=True)

xG_mean_df = (
    xG_mean_possession
    .groupby(['teamId', 'teamName']).agg(
          matches=('teamName', 'size'),
          total_xG=('xG', 'sum'),
          avg_xG=('xG', 'mean'),
          total_xG_open_play=('xG_open_play', 'sum'),
          avg_xG_open_play=('xG_open_play', 'mean'),
          total_xG_set_play=('xG_set_play', 'sum'),
          avg_xG_set_play=('xG_set_play', 'mean'),
          total_xG_non_penalty=('xG_non_penalty', 'sum'),
          avg_xG_non_penalty=('xG_non_penalty', 'mean'),
          total_xGOT=('xGOT', 'sum'),
          avg_xGOT=('xGOT', 'mean')
      )
      .sort_values('avg_xG', ascending=False)
      .reset_index()
)

xG_mean_df.tail()

,teamId,teamName,matches,total_xG,avg_xG,total_xG_open_play,avg_xG_open_play,total_xG_set_play,avg_xG_set_play,total_xG_non_penalty,avg_xG_non_penalty,total_xGOT,avg_xGOT
43,5902,Qatar,3,1.59,0.530000,1.36,0.453333,0.23,0.076667,1.59,0.530000,1.60,0.533333
44,287981,Curacao,3,1.41,0.470000,1.01,0.336667,0.40,0.133333,1.41,0.470000,1.44,0.480000
45,7795,Saudi Arabia,3,1.19,0.396667,0.57,0.190000,0.62,0.206667,1.19,0.396667,1.08,0.360000
46,6719,Tunisia,3,0.95,0.316667,0.33,0.110000,0.62,0.206667,0.95,0.316667,1.29,0.430000
47,6724,Paraguay,5,1.58,0.316000,0.85,0.170000,0.74,0.148000,1.58,0.316000,1.42,0.284000

In [5]:
# MEAN

# ball_possession_home

# Create a dataframe with home teams data
mean_home_df = df[['homeTeamName', 'homeTeamid', 'ball_possession_home']].rename(
    columns={
        'homeTeamName': 'teamName',
        'homeTeamid': 'teamId',
        'ball_possession_home': 'ball_possession'
    }
)

# Create a dataframe with away teams data
mean_away_df = df[['awayTeamName', 'awayTeamid', 'ball_possession_away']].rename(
    columns={
        'awayTeamName': 'teamName',
        'awayTeamid': 'teamId',
        'ball_possession_away': 'ball_possession'
    }
)

# Stack both dataframes together
mean_possession = pd.concat([mean_home_df, mean_away_df], ignore_index=True)

# Mean
ball_possession_df = (
    mean_possession
    .groupby(['teamId', 'teamName'], as_index=False)[['ball_possession']]
    .mean()
    .rename(columns={'ball_possession': 'mean_ball_possession'})
    .sort_values('mean_ball_possession', ascending=False)
)

ball_possession_df

    teamId                teamName  mean_ball_possession
14    6595                 Turkiye             65.666667
42    8570                 Germany             65.250000
27    6720                   Spain             63.875000
31    7804             South Korea             62.666667
11    6317                 Algeria             61.250000
9     6262                 Morocco             59.000000
36    8361                Portugal             58.200000
15    6706               Argentina             57.625000
34    8258                Colombia             57.600000
21    6713                     USA             56.800000
28    6723                  France             55.875000
16    6707                 Ecuador             55.750000
13    6395                 Senegal             55.250000
0     5796                 Uruguay             55.000000
1     5810                  Canada             54.400000
37    8491                 England             54.125000
25    6717             Switzerland             53.833333
17    6708             Netherlands             53.000000
33    8256                  Brazil             53.000000
38    8492                  Norway             52.166667
19    6710                  Mexico             52.000000
46   10255                   Egypt             51.400000
35    8263                 Belgium             51.000000
45   10155                 Croatia             49.750000
18    6709             Ivory Coast             49.750000
10    6316            South Africa             48.000000
4     5820             New Zealand             47.333333
23    6715                   Japan             46.250000
41    8520                  Sweden             46.250000
44   10106  Bosnia and Herzegovina             45.750000
7     5922                  Panama             45.666667
32    8255                 Austria             45.000000
40    8498                Scotland             44.333333
8     5934                   Haiti             42.666667
39    8496                 Czechia             42.666667
24    6716               Australia             41.000000
12    6321                DR Congo             39.750000
26    6719                 Tunisia             39.333333
20    6711                    Iran             39.000000
30    7795            Saudi Arabia             38.333333
43    8700              Uzbekistan             38.333333
3     5819                    Iraq             38.000000
5     5888              Cape Verde             37.000000
22    6714                   Ghana             36.250000
6     5902                   Qatar             33.000000
47  287981                 Curacao             32.333333
2     5816                  Jordan             30.666667
29    6724                Paraguay             29.800000

In [6]:
# Columns to SUM

# home_goals, big_chances_home, big_chances_missed_home, corners_home, total_shots_home, shots_off_target_home, blocked_shots_home, hit_woodwork_home, shots_inside_box_home, shots_outside_box_home,
# passes_home, own_half_passes_home, opposition_half_passes_home, throws_home, touches_opp_box_home, offsides_home, tackles_won_home, interceptions_home, blocks_home, clearances_home, keeper_saves_home,
# duel_won_home, yellow_cards_home, red_cards_home

# Create a dataframe with home teams data
home_df = df[['homeTeamName', 'homeTeamid', 'home_goals', 'big_chances_home', 'big_chances_missed_home', 'corners_home', 'total_shots_home', 'shots_off_target_home', 'shots_on_target_home', 'blocked_shots_home',
              'hit_woodwork_home', 'shots_inside_box_home', 'shots_outside_box_home', 'passes_home', 'own_half_passes_home', 'opposition_half_passes_home', 'throws_home', 'touches_opp_box_home',
              'offsides_home', 'tackles_won_home', 'interceptions_home', 'blocks_home', 'clearances_home', 'keeper_saves_home', 'duel_won_home', 'yellow_cards_home', 'red_cards_home']].rename(
    columns={
        'homeTeamName': 'teamName',
        'homeTeamid': 'teamId',
        'home_goals': 'goals',
        'big_chances_home': 'big_chances',
        'big_chances_missed_home': 'big_chances_missed',
        'corners_home': 'corners',
        'total_shots_home': 'total_shots',
        'shots_off_target_home': 'shots_off_target',
        'shots_on_target_home': 'shots_on_target',
        'blocked_shots_home': 'blocked_shots',
        'hit_woodwork_home': 'hit_woodwork',
        'shots_inside_box_home': 'shots_inside_box',
        'shots_outside_box_home': 'shots_outside_box',
        'passes_home': 'passes',
        'own_half_passes_home': 'own_half_passes',
        'opposition_half_passes_home': 'opposition_half_passes',
        'throws_home': 'throws',
        'touches_opp_box_home': 'touches_opp_box',
        'offsides_home': 'offsides',
        'tackles_won_home': 'tackles_won',
        'interceptions_home': 'interceptions',
        'blocks_home': 'blocks',
        'clearances_home': 'clearances',
        'keeper_saves_home': 'keeper_saves',
        'duel_won_home': 'duel_won',
        'yellow_cards_home': 'yellow_cards',
        'red_cards_home': 'red_cards'
    }
)

# Create a dataframe with away teams data
away_df = df[['awayTeamName', 'awayTeamid', 'away_goals', 'big_chances_away', 'big_chances_missed_away', 'corners_away', 'total_shots_away', 'shots_off_target_away', 'shots_on_target_away', 'blocked_shots_away',
              'hit_woodwork_away', 'shots_inside_box_away', 'shots_outside_box_away', 'passes_away', 'own_half_passes_away', 'opposition_half_passes_away', 'throws_away', 'touches_opp_box_away',
              'offsides_away', 'tackles_won_away', 'interceptions_away', 'blocks_away', 'clearances_away', 'keeper_saves_away', 'duel_won_away', 'yellow_cards_away', 'red_cards_away']].rename(
    columns={
        'awayTeamName': 'teamName',
        'awayTeamid': 'teamId',
        'away_goals': 'goals',
        'big_chances_away': 'big_chances',
        'big_chances_missed_away': 'big_chances_missed',
        'corners_away': 'corners',
        'total_shots_away': 'total_shots',
        'shots_off_target_away': 'shots_off_target',
        'shots_on_target_away': 'shots_on_target',
        'blocked_shots_away': 'blocked_shots',
        'hit_woodwork_away': 'hit_woodwork',
        'shots_inside_box_away': 'shots_inside_box',
        'shots_outside_box_away': 'shots_outside_box',
        'passes_away': 'passes',
        'own_half_passes_away': 'own_half_passes',
        'opposition_half_passes_away': 'opposition_half_passes',
        'throws_away': 'throws',
        'touches_opp_box_away': 'touches_opp_box',
        'offsides_away': 'offsides',
        'tackles_won_away': 'tackles_won',
        'interceptions_away': 'interceptions',
        'blocks_away': 'blocks',
        'clearances_away': 'clearances',
        'keeper_saves_away': 'keeper_saves',
        'duel_won_away': 'duel_won',
        'yellow_cards_away': 'yellow_cards',
        'red_cards_away': 'red_cards'
    }
)

# Stack both dataframes together
teams_goals = pd.concat([home_df, away_df], ignore_index=True)

# Sum
sum_df = (
    teams_goals
    .groupby(['teamId', 'teamName'], as_index=False)[['goals', 'big_chances', 'big_chances_missed', 'corners', 'total_shots', 'shots_off_target', 'shots_on_target', 'blocked_shots', 'hit_woodwork', 'shots_inside_box',
                                                      'shots_outside_box', 'passes', 'own_half_passes', 'opposition_half_passes', 'throws', 'touches_opp_box', 'offsides', 'tackles_won', 'interceptions',
                                                      'blocks', 'clearances', 'keeper_saves', 'duel_won', 'yellow_cards', 'red_cards']]
    .sum()
    .sort_values('goals', ascending=False)
)

sum_df

,teamId,teamName,goals,big_chances,big_chances_missed,corners,total_shots,shots_off_target,shots_on_target,blocked_shots,...,touches_opp_box,offsides,tackles_won,interceptions,blocks,clearances,keeper_saves,duel_won,yellow_cards,red_cards
37,8491,England,20,235,33,8.0,118,37,53,28,...,235,15,127,50,25,188,20,429,8,1
28,6723,France,20,249,33,6.0,139,52,59,28,...,249,14,116,69,18,132,13,356,6,0
15,6706,Argentina,19,202,22,13.0,114,44,44,26,...,202,22,159,80,19,185,20,402,13,1
35,8263,Belgium,14,221,15,6.0,112,44,34,34,...,221,8,85,49,17,144,16,300,6,1
27,6720,Spain,14,271,24,6.0,140,54,54,32,...,271,21,127,63,13,135,10,370,6,0
38,8492,Norway,13,143,22,3.0,66,21,29,16,...,143,5,99,43,15,140,21,261,3,0
42,8570,Germany,11,158,16,3.0,74,21,28,25,...,158,4,78,27,9,62,5,205,3,0
17,6708,Netherlands,11,114,6,3.0,46,14,22,10,...,114,8,53,36,5,86,16,179,3,0
21,6713,USA,11,144,12,7.0,59,23,19,17,...,144,11,75,54,12,124,8,269,7,1
9,6262,Morocco,10,121,17,7.0,69,25,26,18,...,121,9,104,44,20,138,15,310,7,0
13,6395,Senegal,10,121,16,3.0,69,32,23,14,...,121,10,54,31,14,76,12,196,3,0
19,6710,Mexico,10,98,13,4.0,70,31,21,18,...,98,5,64,35,7,117,8,213,4,1
25,6717,Switzerland,10,157,16,6.0,74,25,30,19,...,157,13,86,51,18,160,20,302,6,1
33,8256,Brazil,10,149,21,8.0,74,25,30,19,...,149,11,93,48,13,100,14,236,8,0
1,5810,Canada,9,216,16,11.0,80,25,31,24,...,216,7,79,36,3,69,6,263,11,0
36,8361,Portugal,8,108,13,7.0,62,29,17,16,...,108,10,68,33,17,90,19,227,7,0
23,6715,Japan,8,58,6,4.0,34,13,13,8,...,58,4,52,19,11,142,12,150,4,0
46,10255,Egypt,8,127,10,12.0,67,23,18,26,...,127,4,91,43,22,173,14,282,12,0
41,8520,Sweden,7,75,8,5.0,48,15,23,10,...,75,9,52,28,8,84,14,171,5,0
32,8255,Austria,6,74,9,5.0,32,21,8,3,...,74,11,56,40,16,79,13,148,5,0
45,10155,Croatia,6,62,9,4.0,37,13,17,7,...,62,8,66,28,13,97,10,189,4,0
18,6709,Ivory Coast,5,130,10,4.0,45,22,14,9,...,130,4,74,40,13,85,9,199,4,0
44,10106,Bosnia and Herzegovina,5,49,3,7.0,37,13,14,10,...,49,2,59,32,11,155,6,192,7,1
34,8258,Colombia,5,125,15,8.0,94,39,30,25,...,125,19,64,40,14,100,6,208,8,0
12,6321,DR Congo,5,61,5,6.0,41,24,9,8,...,61,9,72,22,12,107,14,180,6,0
11,6317,Algeria,5,81,8,3.0,44,16,15,13,...,81,4,74,33,4,59,8,195,3,0
4,5820,New Zealand,4,44,5,4.0,31,10,15,6,...,44,4,35,25,22,83,11,117,4,0
5,5888,Cape Verde,4,51,3,5.0,49,20,12,17,...,51,7,68,50,23,149,18,207,5,0
24,6716,Australia,3,86,1,5.0,42,17,12,13,...,86,1,58,29,25,120,14,234,5,0
2,5816,Jordan,3,38,2,4.0,24,11,9,4,...,38,3,61,34,8,88,8,142,4,0
14,6595,Turkiye,3,123,12,2.0,71,29,16,26,...,123,7,61,19,8,82,8,170,2,0
0,5796,Uruguay,3,87,5,5.0,49,21,13,15,...,87,14,44,31,6,42,4,140,5,1
29,6724,Paraguay,3,46,4,9.0,35,16,8,11,...,46,5,132,54,31,181,23,308,9,1
20,6711,Iran,3,66,8,6.0,37,17,11,9,...,66,9,58,31,13,110,15,168,6,0
39,8496,Czechia,2,42,4,1.0,34,19,8,7,...,42,5,33,20,13,63,9,125,1,0
10,6316,South Africa,2,43,2,5.0,39,15,11,13,...,43,8,67,46,11,114,11,182,5,2
6,5902,Qatar,2,25,4,4.0,17,10,6,1,...,25,4,43,25,28,116,12,98,4,2
31,7804,South Korea,2,53,8,4.0,32,13,11,8,...,53,8,36,18,5,60,9,148,4,0
8,5934,Haiti,2,48,2,7.0,31,16,7,8,...,48,7,53,31,8,68,11,149,7,0
16,6707,Ecuador,2,98,10,8.0,53,25,20,8,...,98,2,77,38,11,84,9,193,8,1
43,8700,Uzbekistan,2,18,1,4.0,18,8,5,5,...,18,3,57,33,8,91,6,142,4,0
22,6714,Ghana,2,41,4,6.0,24,10,4,10,...,41,8,64,30,14,89,16,178,6,0
26,6719,Tunisia,2,29,2,1.0,18,9,6,3,...,29,9,56,28,13,71,6,127,1,0
3,5819,Iraq,1,30,2,4.0,21,12,2,7,...,30,1,55,22,11,83,11,139,4,1
40,8498,Scotland,1,68,4,5.0,29,14,7,8,...,68,2,44,17,14,47,8,126,5,0
30,7795,Saudi Arabia,1,32,2,6.0,17,5,7,5,...,32,3,55,33,13,103,16,133,6,0
47,287981,Curacao,1,40,0,7.0,29,17,7,5,...,40,5,50,39,12,74,20,147,7,0
7,5922,Panama,0,52,3,5.0,32,18,7,7,...,52,6,55,16,6,80,7,158,5,0

In [7]:
# clean columns 467 (90%)
# fouls_home, accurate_passes_home, accurate_long_passes_home, accurate_crosses_home, ground_duels_won_home, aerial_won_home, dribbles_succeeded_home

df_to_clean = df[['homeTeamid', 'homeTeamName', 'awayTeamid', 'awayTeamName', 'fouls_home', 'fouls_away', 'accurate_passes_home', 'accurate_passes_away', 'accurate_long_passes_home', 'accurate_long_passes_away', 'accurate_crosses_home', 'accurate_crosses_away',
                       'ground_duels_won_home', 'ground_duels_won_away', 'aerial_won_home', 'aerial_won_away', 'dribbles_succeeded_home', 'dribbles_succeeded_away']]

df_to_clean

,homeTeamid,homeTeamName,awayTeamid,awayTeamName,fouls_home,fouls_away,accurate_passes_home,accurate_passes_away,accurate_long_passes_home,accurate_long_passes_away,accurate_crosses_home,accurate_crosses_away,ground_duels_won_home,ground_duels_won_away,aerial_won_home,aerial_won_away,dribbles_succeeded_home,dribbles_succeeded_away
0,6710,Mexico,6316,South Africa,467 (90%),272 (81%),467 (90%),272 (81%),31 (65%),17 (37%),4 (33%),1 (13%),32 (55%),26 (45%),15 (68%),7 (32%),9 (60%),1 (17%)
1,7804,South Korea,8496,Czechia,469 (87%),230 (70%),469 (87%),230 (70%),30 (49%),23 (33%),3 (25%),3 (20%),29 (57%),22 (43%),27 (63%),16 (37%),8 (57%),4 (57%)
2,5810,Canada,10106,Bosnia and Herzegovina,310 (74%),170 (63%),310 (74%),170 (63%),19 (44%),18 (29%),5 (21%),6 (60%),50 (58%),36 (42%),20 (32%),43 (68%),7 (47%),5 (23%)
3,6713,USA,6724,Paraguay,509 (85%),232 (73%),509 (85%),232 (73%),26 (54%),20 (34%),3 (16%),0 (0%),47 (55%),39 (45%),18 (53%),16 (47%),22 (63%),6 (60%)
4,5902,Qatar,6717,Switzerland,200 (72%),527 (91%),200 (72%),527 (91%),19 (30%),27 (77%),1 (11%),6 (17%),26 (49%),27 (51%),10 (50%),10 (50%),2 (50%),7 (54%)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,6706,Argentina,6717,Switzerland,614 (89%),398 (84%),614 (89%),398 (84%),22 (43%),22 (42%),7 (32%),3 (16%),42 (58%),30 (42%),20 (59%),14 (41%),12 (75%),5 (36%)
100,6723,France,6720,Spain,395 (84%),427 (85%),395 (84%),427 (85%),19 (53%),14 (27%),4 (20%),1 (14%),36 (51%),35 (49%),8 (32%),17 (68%),11 (46%),2 (40%)
101,8491,England,6706,Argentina,273 (84%),537 (91%),273 (84%),537 (91%),16 (38%),13 (48%),3 (19%),6 (30%),37 (46%),43 (54%),13 (59%),9 (41%),7 (37%),13 (81%)
102,6723,France,8491,England,404 (91%),469 (91%),404 (91%),469 (91%),17 (65%),15 (43%),0 (0%),4 (33%),31 (33%),64 (67%),8 (62%),5 (38%),7 (37%),23 (85%)
103,6720,Spain,6706,Argentina,763 (89%),357 (77%),763 (89%),357 (77%),23 (44%),25 (34%),5 (19%),1 (14%),51 (52%),48 (48%),13 (52%),12 (48%),14 (56%),9 (64%)

In [26]:
# ✖️✖️✖️
# clean (%) with regex
# 👇 fixed code

cleaned_df = pd.DataFrame()

cleaned_df['fouls_home'] = df_to_clean['fouls_home'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['fouls_away'] = df_to_clean['fouls_away'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['accurate_passes_home'] = df_to_clean['accurate_passes_home'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['accurate_passes_away'] = df_to_clean['accurate_passes_away'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['accurate_long_passes_home'] = df_to_clean['accurate_long_passes_home'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['accurate_long_passes_away'] = df_to_clean['accurate_long_passes_away'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['accurate_crosses_home'] = df_to_clean['accurate_crosses_home'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['accurate_crosses_away'] = df_to_clean['accurate_crosses_away'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['ground_duels_won_home'] = df_to_clean['ground_duels_won_home'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['ground_duels_won_away'] = df_to_clean['ground_duels_won_away'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['aerial_won_home'] = df_to_clean['aerial_won_home'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['aerial_won_away'] = df_to_clean['aerial_won_away'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['dribbles_succeeded_home'] = df_to_clean['dribbles_succeeded_home'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)
cleaned_df['dribbles_succeeded_away'] = df_to_clean['dribbles_succeeded_away'].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)

cleaned_df

,fouls_home,fouls_away,accurate_passes_home,accurate_passes_away,accurate_long_passes_home,accurate_long_passes_away,accurate_crosses_home,accurate_crosses_away,ground_duels_won_home,ground_duels_won_away,aerial_won_home,aerial_won_away,dribbles_succeeded_home,dribbles_succeeded_away
0,467,272,467,272,31,17,4,1,32,26,15,7,9,1
1,469,230,469,230,30,23,3,3,29,22,27,16,8,4
2,310,170,310,170,19,18,5,6,50,36,20,43,7,5
3,509,232,509,232,26,20,3,0,47,39,18,16,22,6
4,200,527,200,527,19,27,1,6,26,27,10,10,2,7
5,449,419,449,419,18,17,4,2,41,58,12,4,5,16
6,367,307,367,307,26,30,5,5,38,38,13,21,6,5
7,201,635,201,635,16,19,4,2,27,29,15,17,8,5
8,554,282,554,282,12,17,5,2,38,45,9,5,9,12
9,463,286,463,286,16,13,8,6,25,21,21,7,8,3
10,397,419,397,419,18,11,2,4,41,33,17,11,14,3
11,278,292,278,292,22,24,3,3,26,36,15,15,5,7
12,734,205,734,205,24,19,6,1,21,31,19,9,7,4
13,389,323,389,323,18,18,6,2,38,49,14,8,7,7
14,236,540,236,540,10,24,3,16,18,22,22,20,3,8
15,314,376,314,376,27,21,6,1,29,28,25,15,4,6
16,505,427,505,427,21,25,0,1,31,27,12,8,5,8

In [27]:
# ✖️✖️✖️
# clean (%) with regex
# loop with a mapping dictionary

columns_to_clean = [
    'fouls', 'accurate_passes', 'accurate_long_passes', 
    'accurate_crosses', 'ground_duels_won', 'aerial_won', 
    'dribbles_succeeded'
]

cleaned_df = pd.DataFrame()

for col in columns_to_clean:
    for suffix in ['home', 'away']:
        original_col = f'{col}_{suffix}'
        cleaned_df[original_col] = df_to_clean[original_col].str.replace(r'\s*\(.*\)', '', regex=True).astype(int)

cleaned_df

,fouls_home,fouls_away,accurate_passes_home,accurate_passes_away,accurate_long_passes_home,accurate_long_passes_away,accurate_crosses_home,accurate_crosses_away,ground_duels_won_home,ground_duels_won_away,aerial_won_home,aerial_won_away,dribbles_succeeded_home,dribbles_succeeded_away
0,467,272,467,272,31,17,4,1,32,26,15,7,9,1
1,469,230,469,230,30,23,3,3,29,22,27,16,8,4
2,310,170,310,170,19,18,5,6,50,36,20,43,7,5
3,509,232,509,232,26,20,3,0,47,39,18,16,22,6
4,200,527,200,527,19,27,1,6,26,27,10,10,2,7
5,449,419,449,419,18,17,4,2,41,58,12,4,5,16
6,367,307,367,307,26,30,5,5,38,38,13,21,6,5
7,201,635,201,635,16,19,4,2,27,29,15,17,8,5
8,554,282,554,282,12,17,5,2,38,45,9,5,9,12
9,463,286,463,286,16,13,8,6,25,21,21,7,8,3
10,397,419,397,419,18,11,2,4,41,33,17,11,14,3
11,278,292,278,292,22,24,3,3,26,36,15,15,5,7
12,734,205,734,205,24,19,6,1,21,31,19,9,7,4
13,389,323,389,323,18,18,6,2,38,49,14,8,7,7
14,236,540,236,540,10,24,3,16,18,22,22,20,3,8
15,314,376,314,376,27,21,6,1,29,28,25,15,4,6
16,505,427,505,427,21,25,0,1,31,27,12,8,5,8

In [8]:
# ✔️✔️✔️ FINAL code for cleaning df

columns_to_clean = [
    'fouls', 'accurate_passes', 'accurate_long_passes', 
    'accurate_crosses', 'ground_duels_won', 'aerial_won', 
    'dribbles_succeeded'
]

cleaned_df = df_to_clean.copy()

for col in columns_to_clean:
    for suffix in ['home', 'away']:
        original_col = f'{col}_{suffix}'
        cleaned_df[original_col] = (
            cleaned_df[original_col]
            .str.replace(r'\s*\(.*\)', '', regex=True)
            .astype(int)
        )

cleaned_df

,homeTeamid,homeTeamName,awayTeamid,awayTeamName,fouls_home,fouls_away,accurate_passes_home,accurate_passes_away,accurate_long_passes_home,accurate_long_passes_away,accurate_crosses_home,accurate_crosses_away,ground_duels_won_home,ground_duels_won_away,aerial_won_home,aerial_won_away,dribbles_succeeded_home,dribbles_succeeded_away
0,6710,Mexico,6316,South Africa,467,272,467,272,31,17,4,1,32,26,15,7,9,1
1,7804,South Korea,8496,Czechia,469,230,469,230,30,23,3,3,29,22,27,16,8,4
2,5810,Canada,10106,Bosnia and Herzegovina,310,170,310,170,19,18,5,6,50,36,20,43,7,5
3,6713,USA,6724,Paraguay,509,232,509,232,26,20,3,0,47,39,18,16,22,6
4,5902,Qatar,6717,Switzerland,200,527,200,527,19,27,1,6,26,27,10,10,2,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,6706,Argentina,6717,Switzerland,614,398,614,398,22,22,7,3,42,30,20,14,12,5
100,6723,France,6720,Spain,395,427,395,427,19,14,4,1,36,35,8,17,11,2
101,8491,England,6706,Argentina,273,537,273,537,16,13,3,6,37,43,13,9,7,13
102,6723,France,8491,England,404,469,404,469,17,15,0,4,31,64,8,5,7,23
103,6720,Spain,6706,Argentina,763,357,763,357,23,25,5,1,51,48,13,12,14,9

In [9]:
# SUM succeeded data
# fouls_home, accurate_passes_home, accurate_long_passes_home, accurate_crosses_home, ground_duels_won_home, aerial_won_home, dribbles_succeeded_home

# Create a dataframe with home teams data
succeed_home_df = cleaned_df[['homeTeamName', 'homeTeamid', 'fouls_home', 'accurate_passes_home', 'accurate_long_passes_home', 'accurate_crosses_home', 'ground_duels_won_home',
                      'aerial_won_home', 'dribbles_succeeded_home']].rename(
    columns={
        'homeTeamName': 'teamName',
        'homeTeamid': 'teamId',
        'fouls_home': 'fouls',
        'accurate_passes_home': 'accurate_passes',
        'accurate_long_passes_home': 'accurate_long_passes',
        'accurate_crosses_home': 'accurate_crosses',
        'ground_duels_won_home': 'ground_duels_won',
        'aerial_won_home': 'aerial_won',
        'dribbles_succeeded_home': 'dribbles_succeeded'        
    }
)

# Create a dataframe with away teams data
succeed_away_df = cleaned_df[['awayTeamName', 'awayTeamid', 'fouls_away', 'accurate_passes_away', 'accurate_long_passes_away', 'accurate_crosses_away', 'ground_duels_won_away',
                      'aerial_won_away', 'dribbles_succeeded_away']].rename(
    columns={
        'awayTeamName': 'teamName',
        'awayTeamid': 'teamId',
        'fouls_away': 'fouls',
        'accurate_passes_away': 'accurate_passes',
        'accurate_long_passes_away': 'accurate_long_passes',
        'accurate_crosses_away': 'accurate_crosses',
        'ground_duels_won_away': 'ground_duels_won',
        'aerial_won_away': 'aerial_won',
        'dribbles_succeeded_away': 'dribbles_succeeded'
    }
)

# Stack both dataframes together
succeed_sum_df = pd.concat([succeed_home_df, succeed_away_df], ignore_index=True)

succeed_df = (
    succeed_sum_df
    .groupby(['teamId', 'teamName'], as_index=False)[['fouls', 'accurate_passes', 'accurate_long_passes', 'accurate_crosses', 'ground_duels_won', 'aerial_won',
                                                      'dribbles_succeeded']]
    .sum()
    .sort_values('accurate_passes', ascending=False)
)

succeed_df

,teamId,teamName,fouls,accurate_passes,accurate_long_passes,accurate_crosses,ground_duels_won,aerial_won,dribbles_succeeded
27,6720,Spain,4780,4780,165,32,271,99,59
15,6706,Argentina,4563,4563,147,33,322,80,66
28,6723,France,3750,3750,156,19,263,93,77
37,8491,England,3454,3454,145,43,327,102,86
9,6262,Morocco,3137,3137,97,18,253,57,62
25,6717,Switzerland,2712,2712,144,16,218,84,45
38,8492,Norway,2630,2630,124,22,177,84,38
36,8361,Portugal,2581,2581,126,23,176,51,49
35,8263,Belgium,2563,2563,121,32,208,92,56
34,8258,Colombia,2388,2388,147,20,154,54,27
33,8256,Brazil,2379,2379,88,17,180,56,35
42,8570,Germany,2350,2350,73,24,156,49,36
11,6317,Algeria,2308,2308,89,7,159,36,46
46,10255,Egypt,2197,2197,108,21,197,85,44
21,6713,USA,2159,2159,104,17,199,70,60
13,6395,Senegal,1911,1911,119,21,137,59,36
19,6710,Mexico,1812,1812,136,26,140,73,30
17,6708,Netherlands,1755,1755,65,20,113,66,18
1,5810,Canada,1666,1666,76,37,183,80,33
18,6709,Ivory Coast,1661,1661,84,17,155,44,46
16,6707,Ecuador,1653,1653,66,21,143,50,28
45,10155,Croatia,1602,1602,71,17,142,47,29
31,7804,South Korea,1598,1598,82,15,88,60,23
14,6595,Turkiye,1529,1529,71,10,126,44,27
10,6316,South Africa,1523,1523,97,8,140,42,27
32,8255,Austria,1519,1519,57,12,103,45,20
23,6715,Japan,1446,1446,73,14,97,53,16
44,10106,Bosnia and Herzegovina,1274,1274,73,9,119,73,22
24,6716,Australia,1261,1261,72,19,137,97,44
41,8520,Sweden,1229,1229,57,13,121,50,23
5,5888,Cape Verde,1200,1200,89,10,152,55,38
0,5796,Uruguay,1188,1188,62,21,95,45,22
40,8498,Scotland,1145,1145,67,17,93,33,11
22,6714,Ghana,1133,1133,81,9,136,42,27
12,6321,DR Congo,1120,1120,71,12,142,38,25
4,5820,New Zealand,1082,1082,57,6,79,38,21
7,5922,Panama,982,982,84,13,108,50,23
29,6724,Paraguay,916,916,88,8,227,81,38
8,5934,Haiti,897,897,78,10,116,33,20
30,7795,Saudi Arabia,889,889,45,6,96,37,17
3,5819,Iraq,868,868,57,10,109,30,24
39,8496,Czechia,835,835,65,15,83,42,19
20,6711,Iran,793,793,74,9,95,73,14
26,6719,Tunisia,775,775,60,9,99,28,11
43,8700,Uzbekistan,774,774,47,5,103,39,18
47,287981,Curacao,736,736,46,8,113,34,33
6,5902,Qatar,675,675,52,7,77,21,7
2,5816,Jordan,650,650,60,7,113,29,31

In [10]:
# JOIN sum_df & succeed_df

final_df = pd.merge(
    succeed_df,
    sum_df,
    on=['teamId', 'teamName'],
    how='inner'  # keeps only matching teamIds
)

final_df.head()

,teamId,teamName,fouls,accurate_passes,accurate_long_passes,accurate_crosses,ground_duels_won,aerial_won,dribbles_succeeded,goals,...,touches_opp_box,offsides,tackles_won,interceptions,blocks,clearances,keeper_saves,duel_won,yellow_cards,red_cards
0,6720,Spain,4780,4780,165,32,271,99,59,14,...,271,21,127,63,13,135,10,370,6,0
1,6706,Argentina,4563,4563,147,33,322,80,66,19,...,202,22,159,80,19,185,20,402,13,1
2,6723,France,3750,3750,156,19,263,93,77,20,...,249,14,116,69,18,132,13,356,6,0
3,8491,England,3454,3454,145,43,327,102,86,20,...,235,15,127,50,25,188,20,429,8,1
4,6262,Morocco,3137,3137,97,18,253,57,62,10,...,121,9,104,44,20,138,15,310,7,0

In [11]:
# JOIN the 4 data frames

join_df = (
    xG_mean_df
    .merge(ball_possession_df, on=['teamId', 'teamName'], how='inner')
    .merge(final_df, on=['teamId', 'teamName'], how='inner')
)

join_df

,teamId,teamName,matches,total_xG,avg_xG,total_xG_open_play,avg_xG_open_play,total_xG_set_play,avg_xG_set_play,total_xG_non_penalty,...,touches_opp_box,offsides,tackles_won,interceptions,blocks,clearances,keeper_saves,duel_won,yellow_cards,red_cards
0,8256,Brazil,5,11.67,2.334000,9.61,1.922000,0.50,0.100000,10.10,...,149,11,93,48,13,100,14,236,8,0
1,6395,Senegal,4,8.83,2.207500,6.83,1.707500,2.49,0.622500,8.44,...,121,10,54,31,14,76,12,196,3,0
2,6723,France,8,17.44,2.180000,13.90,1.737500,3.86,0.482500,15.97,...,249,14,116,69,18,132,13,356,6,0
3,6595,Turkiye,3,6.54,2.180000,5.05,1.683333,1.49,0.496667,6.54,...,123,7,61,19,8,82,8,170,2,0
4,8570,Germany,4,8.27,2.067500,6.33,1.582500,1.14,0.285000,7.48,...,158,4,78,27,9,62,5,205,3,0
5,6720,Spain,8,15.63,1.953750,12.24,1.530000,2.58,0.322500,14.85,...,271,21,127,63,13,135,10,370,6,0
6,5810,Canada,5,9.73,1.946000,6.60,1.320000,3.11,0.622000,9.73,...,216,7,79,36,3,69,6,263,11,0
7,6706,Argentina,8,14.66,1.832500,9.03,1.128750,3.26,0.407500,12.30,...,202,22,159,80,19,185,20,402,13,1
8,8263,Belgium,6,10.83,1.805000,7.49,1.248333,2.55,0.425000,10.05,...,221,8,85,49,17,144,16,300,6,1
9,8491,England,8,14.34,1.792500,9.40,1.175000,2.57,0.321250,11.97,...,235,15,127,50,25,188,20,429,8,1
10,8492,Norway,6,10.04,1.673333,7.10,1.183333,2.16,0.360000,9.25,...,143,5,99,43,15,140,21,261,3,0
11,6717,Switzerland,6,9.68,1.613333,6.91,1.151667,1.20,0.200000,8.10,...,157,13,86,51,18,160,20,302,6,1
12,8258,Colombia,5,7.42,1.484000,6.05,1.210000,1.37,0.274000,7.42,...,125,19,64,40,14,100,6,208,8,0
13,6707,Ecuador,4,5.87,1.467500,3.54,0.885000,2.34,0.585000,5.87,...,98,2,77,38,11,84,9,193,8,1
14,5796,Uruguay,3,4.24,1.413333,2.98,0.993333,1.26,0.420000,4.24,...,87,14,44,31,6,42,4,140,5,1
15,6262,Morocco,6,8.46,1.410000,7.63,1.271667,0.84,0.140000,8.46,...,121,9,104,44,20,138,15,310,7,0
16,6709,Ivory Coast,4,5.55,1.387500,4.96,1.240000,0.59,0.147500,5.55,...,130,4,74,40,13,85,9,199,4,0
17,6708,Netherlands,4,5.48,1.370000,4.18,1.045000,1.30,0.325000,5.48,...,114,8,53,36,5,86,16,179,3,0
18,7804,South Korea,3,4.11,1.370000,3.52,1.173333,0.59,0.196667,4.11,...,53,8,36,18,5,60,9,148,4,0
19,8361,Portugal,5,6.82,1.364000,4.07,0.814000,1.96,0.392000,6.04,...,108,10,68,33,17,90,19,227,7,0
20,6711,Iran,3,4.09,1.363333,2.08,0.693333,1.21,0.403333,3.30,...,66,9,58,31,13,110,15,168,6,0
21,6710,Mexico,5,6.66,1.332000,4.80,0.960000,1.08,0.216000,5.87,...,98,5,64,35,7,117,8,213,4,1
22,6713,USA,5,6.14,1.228000,4.19,0.838000,1.96,0.392000,6.14,...,144,11,75,54,12,124,8,269,7,1
23,10255,Egypt,5,5.99,1.198000,4.92,0.984000,1.07,0.214000,5.99,...,127,4,91,43,22,173,14,282,12,0
24,6317,Algeria,4,4.62,1.155000,3.38,0.845000,1.24,0.310000,4.62,...,81,4,74,33,4,59,8,195,3,0
25,6321,DR Congo,4,4.19,1.047500,2.41,0.602500,0.97,0.242500,3.40,...,61,9,72,22,12,107,14,180,6,0
26,6715,Japan,4,4.16,1.040000,3.60,0.900000,0.56,0.140000,4.16,...,58,4,52,19,11,142,12,150,4,0
27,10155,Croatia,4,4.11,1.027500,3.33,0.832500,0.77,0.192500,4.11,...,62,8,66,28,13,97,10,189,4,0
28,8255,Austria,4,4.03,1.007500,2.83,0.707500,0.41,0.102500,3.24,...,74,11,56,40,16,79,13,148,5,0
29,8520,Sweden,4,3.68,0.920000,2.53,0.632500,1.16,0.290000,3.68,...,75,9,52,28,8,84,14,171,5,0
30,5820,New Zealand,3,2.72,0.906667,1.18,0.393333,1.53,0.510000,2.72,...,44,4,35,25,22,83,11,117,4,0
31,8498,Scotland,3,2.60,0.866667,1.88,0.626667,0.72,0.240000,2.60,...,68,2,44,17,14,47,8,126,5,0
32,8496,Czechia,3,2.38,0.793333,0.99,0.330000,1.39,0.463333,2.38,...,42,5,33,20,13,63,9,125,1,0
33,5888,Cape Verde,4,2.94,0.735000,2.19,0.547500,0.76,0.190000,2.94,...,51,7,68,50,23,149,18,207,5,0
34,6716,Australia,4,2.92,0.730000,1.72,0.430000,1.20,0.300000,2.92,...,86,1,58,29,25,120,14,234,5,0
35,6316,South Africa,4,2.75,0.687500,1.75,0.437500,0.19,0.047500,1.96,...,43,8,67,46,11,114,11,182,5,2
36,5934,Haiti,3,1.95,0.650000,1.63,0.543333,0.33,0.110000,1.95,...,48,7,53,31,8,68,11,149,7,0
37,5922,Panama,3,1.94,0.646667,1.20,0.400000,0.74,0.246667,1.94,...,52,6,55,16,6,80,7,158,5,0
38,5816,Jordan,3,1.85,0.616667,1.43,0.476667,0.43,0.143333,1.85,...,38,3,61,34,8,88,8,142,4,0
39,6714,Ghana,4,2.39,0.597500,1.62,0.405000,0.75,0.187500,2.39,...,41,8,64,30,14,89,16,178,6,0
40,8700,Uzbekistan,3,1.61,0.536667,1.51,0.503333,0.11,0.036667,1.61,...,18,3,57,33,8,91,6,142,4,0
41,10106,Bosnia and Herzegovina,4,2.14,0.535000,0.75,0.187500,1.40,0.350000,2.14,...,49,2,59,32,11,155,6,192,7,1
42,5819,Iraq,3,1.60,0.533333,1.15,0.383333,0.45,0.150000,1.60,...,30,1,55,22,11,83,11,139,4,1
43,5902,Qatar,3,1.59,0.530000,1.36,0.453333,0.23,0.076667,1.59,...,25,4,43,25,28,116,12,98,4,2
44,287981,Curacao,3,1.41,0.470000,1.01,0.336667,0.40,0.133333,1.41,...,40,5,50,39,12,74,20,147,7,0
45,7795,Saudi Arabia,3,1.19,0.396667,0.57,0.190000,0.62,0.206667,1.19,...,32,3,55,33,13,103,16,133,6,0
46,6719,Tunisia,3,0.95,0.316667,0.33,0.110000,0.62,0.206667,0.95,...,29,9,56,28,13,71,6,127,1,0
47,6724,Paraguay,5,1.58,0.316000,0.85,0.170000,0.74,0.148000,1.58,...,46,5,132,54,31,181,23,308,9,1

In [12]:
len(join_df.columns)

46

In [13]:
# SAVE variable in CSV
join_df.to_csv(r'C:\Users\Public\Documents\Axel\wcup26\data\clean_fotmob_match_stats.csv', index=False)

In [34]:
# Sample data
e_df = pd.DataFrame({
    'values': ['467 (90%)', '123 (45%)', '999 (100%)', '50 (5%)']
})

e_df

       values
0   467 (90%)
1   123 (45%)
2  999 (100%)
3     50 (5%)